### ISSUE TITLE
[Business Partner KIT] Release Checks

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/sig-release#1127]
This issue tracks all relevant release checks for Business Partner KIT.

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Have your prepared content reviewed by a professional peer group before submitting it for committer approval.
Best practice: have a professional Peer review your prepared content before you submit for expert approvals.

Responsible contacts:

Committer(s): @SujitMBRDI
ExpertGroup: @maximilianong 

**Version to be included in Eclipse Tractus-X release:** *7.0.0*
- KIT semantic version of change log 
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.

- [1020](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1020)
- [1096](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1096)

# General

- [x] **CHANGELOG** available and maintained
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [ ] ~**Semantic Models** linked and described~
- [ ] ~**Logic / Schema** available and described~
- [x] **Business Process** documentation available
- [x] **Access and Usage Policies** documented
- [ ] ~**Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)~
- [ ] ~**Tutorials** available~
- [ ] ~**White Paper** available~
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] ~**Protocols** available (e.g., dataspace protocol)~
- [ ] ~**Sample Data** available~
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] ~**Reference Implementation** available~

# Operation View

- [x] **Setup Guide** available (e.g., installation guides)
- [x] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

# Todos

- [x] Review by peer group (members of committees and expert groups)
- [x] Please link the open or merged PR that includes the changes.

**Comment by SujitMBRDI** [comment]
## Known Knowns

- API Specification published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot) 
with restriction, only three applications can be part of swagger hub. So, we have [api-hub](https://eclipse-tractusx.github.io/api-hub/bpdm/6.2.0/) avaible for swagger documentation of business partner management service.

**Comment by stephanbcbauer** [comment]
Since this is 24.12, i am sure it can be closed? @SujitMBRDI
