### ISSUE TITLE
CX-ART Feature (DEMO issue) with example links

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-release#13]
Background:

Target scenario: 

Implementation idea / approach:

- [ ] working group a link a issue https://github.com/SystemGuideOrg/goforit/issues/22
- [ ] working group b https://github.com/SystemGuideOrg/deep-dive/issues/32
- [x] #226

```[tasklist]
### Tasks
- [ ] Draft task
```

**Comment by FaGru3n** [comment]
Closing demo issue to not confuse with actual planning issues

**Comment by mabige** [comment]
test

**Comment by mabige** [comment]
Bitte noch xy berücksichtigen

**Comment by FaGru3n** [comment]
- [ ] task for expert group
- [ ] task for other team
- [ ] task for someone else

**Comment by FaGru3n** [comment]
@dg-tsy fyi
