### ISSUE TITLE
SSI Credential Expiry Setting

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#301]
## Description
It is planned to remove the credential "expiry date" from the MIW component and move the same to the portal (which is currently acting as issuer).
With the push of a credential creation, the issuer (portal) will define the expiry date.

### Details

In the current SSI implementation (Release 3.2) the expiry date of the VC is defined and set by the MIW component.

With the next release - the VC expiry date needs to get set by the issuer.

Following logic is planned for the CX reference solution

#### VC Expiry calculation

Expiry date is set based on the "until_date" defined for the respective credentialType (inside the credential hub)
If VC “until date“ is > 12 month, the VC expiry date is automatically set to "today + 12 month"

Logic

With the VC creation push (by the portal component) the expiry date is getting submitted as part of the VC creation POST call
the newly created VC uses the pushed expiry date
in case no date is submitted, automatically 12 months are set by the VC creation component

#### Implementation Steps

Level 01

MIW to exclude the backend business logic for expiry date creation
MIW to update the credential POST calls by adding inside the request body the property "expiryDate"
MIW to update the credential POST calls backend logic to set the expiry date automatically to 12 month in case no expiry date is getting submitted
Portal to add in the credential POST calls the expiry date per credential (logic as defined above)

Level 02

MIW to exclude/delete all POST credential endpoints incl. the backend logic
New VC creation component to be implemented where the logic of the expiry date is getting added

#### Expiry Result Based on Date - What happens if a credential expires?

=> Issuer (for the reference solution the portal) informs the VC holder about expiries with 1 month, 2-weeks and 1-day pre-info)

=> Expired VCs should get removed after a certain time (time to be defined - not urgent)

=> EDCs need to validate if the VC is expired or not

=> Portal to allow re-issuance of VCs as soon as the VC expiry is soon taking place

## Impact
Portal & MIW

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by OSchlienz** [comment]
Has a relation to the summary credential, process flows if there are several expiry dates
--> makes sense after summary credential is obsolete (if not all the logic would have to be adapted)

**Comment by stephanbcbauer** [comment]
Hello @jjeroch , @evegufy  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by jjeroch** [comment]
The function is delivered - MIW got descoped but rest works as designed
