### ISSUE TITLE
Contract Offer Management Feature for Dataspace Participants

### ISSUE THREAD

**Issue by dg-tsy** [eclipse-tractusx/sig-release#337]
## Description
**As a** data space participant

**I require a set of APIs** to simplify and streamline all data governance related activities for Contract Definition/Offer Management Feature within Data Governance Kit e.g.

- Creation of Contract Offer and storing it in DGK staging area
- Get all Contract Offers from DGK staging area
- Edit Contract Offers 
- Delete Contract Offers 

**so that** I can have complete Contract Offer Management Feature implemented with in Data Governance Kit.

## Benefit Hypothesis
For data space participants currently there is no convenient way that allows to manage all Contract Offer related governance topics of a data space participant in a single place, especially when multiple backend data services and/or dataspace apps are in use.

DGK shall provide means which would help to implement such components.

## Scope
API specifications for Contract Offer related governance use cases relevant for dataspace participants (data providers and data consumers)

## Out of Scope
- Implementation
- This feature belongs to Data Governance Kit which would have decentral components deployed in the Provider or Consumer space and is not related to any kind of management for any of the central components.

## Tasks
- [x] https://github.com/eclipse-tractusx/sig-release/issues/435
- [x] https://github.com/eclipse-tractusx/sig-release/issues/440
- [x] https://github.com/eclipse-tractusx/sig-release/issues/441
- [x] https://github.com/eclipse-tractusx/sig-release/issues/442
