### ISSUE TITLE
Enable Umbrella Helm Chart

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#418]
## Description

The purpose of this Feature is to built an umbrella helm chart including seeding data, so that it is possible to have an easy entrance point for new developer, or tech leads, e2e testing, validation of services and to get to know how catena-x works. 

It will include: 
- an highly configurable umbrella helm chart
- seeding data for various purposes (E2E-Testing, Tutorials,...)

### IRS 
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/312

## Impact

Newcomers have an easy entrypoint to learn what catena-x is about and how it can be used. 
With the tutorials #430 built upon this it will be a good way of providing one structured documented way of deploying and testing the FOSS services and applications.

## Additional information 

- https://github.com/eclipse-tractusx/e2e-testing/blob/main/plan.md

**Comment by stephanbcbauer** [comment]
was presented in open planning -> contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @jzbmw, @mkanal 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by mkanal** [comment]
Hello @jjeroch ,
if you agree, I would close the ticket as all work is done and Umbrella HELM is ready and could be used. 
Thank you very much
Martin

**Comment by evegufy** [comment]
### Status

The currently integrated components are following (state R24.03):

- [portal](https://github.com/eclipse-tractusx/portal/tree/portal-1.8.1)
- [centralidp](https://github.com/eclipse-tractusx/portal-iam/tree/v2.1.0)
- [sharedidp](https://github.com/eclipse-tractusx/portal-iam/tree/v2.1.0)
- [bpndiscovery](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.2.2)
- [discoveryfinder](https://github.com/eclipse-tractusx/sldt-discovery-finder/tree/discoveryfinder-0.2.2)
- [sdfactory](https://github.com/eclipse-tractusx/sd-factory/tree/sdfactory-2.1.12)
- [managed-identity-wallet](https://github.com/eclipse-tractusx/managed-identity-wallet/tree/v0.4.0)
- [semantic-hub](https://github.com/eclipse-tractusx/sldt-semantic-hub/tree/semantic-hub-0.2.2)
- [dataconsumerOne](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/tx-data-provider) ([tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc/tree/0.5.3), [vault](https://github.com/hashicorp/vault-helm/tree/v0.20.0))
- [tx-data-provider](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/tx-data-provider) ([tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc/tree/0.5.3), [digital-twin-registry](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/tree/digital-twin-registry-0.4.5), [vault](https://github.com/hashicorp/vault-helm/tree/v0.20.0), [simple-data-backend](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/simple-data-backend))
- [dataconsumerTwo](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/tx-data-provider) ([tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc/tree/0.5.3), [vault](https://github.com/hashicorp/vault-helm/tree/v0.20.0))

Enabled subsets: [Data exchange](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-0.16.0/charts/umbrella/README.md#option-2-1) and [Portal](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-0.16.0/charts/umbrella/README.md#get-to-know-the-portal)

Please have look at the [README.md](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-0.16.0/charts/umbrella/README.md) for a more detailed overview.

As the integration works to enable a sandbox environment (to have an easy entrance point for developers and adopters to experience our developments hands on but also to enable e2e testing) is a continuous effort, I created the following follow up issue: https://github.com/eclipse-tractusx/sig-release/issues/710
