### ISSUE TITLE
End-to-End Adopter Journey Tutorial Extension

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#430]
<img width="1885" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/84396022/4de7b71b-93b4-4fa7-a2df-beff7c84e904">

## Description

We already managed to publish the first version of the E2E Adopter Journey [tutorial](https://eclipse-tractusx.github.io/docs/tutorials/e2e/). It was already tested during the community days and provides a description to deploy (locally) preconfigured services, like:

- three tractus-x edcs
- miw
- databases
- keycloak

With this tutorial and the underlaying resources the user will be able to deploy and play with a local data space.

With this feature we want to work in the feedback we received from the community days, related to the documentation itself. Second big topic are the future extensions, which we would like to implement (add to the ressources), like

- dDTR
- discovery services
- portal
- ...

_note_ the extensions are right now just an idea, cause we have several dependencies, technical and organizational.

Another topic within this feature would be a concept or plan for Continuous update because whenever there is a new version of a used service, we might also have to update the tutorial and release a new version.

## Impact/Dependencies

- provided ressource (umbrella helmchart (vs) terraform -> @jzbmw is working on a similar topic, the results could also have an impact on the tutorial
- the different services we want to add -> is there a need? UseCase for this?
- #418 is the technical feature to provide the ressources (deployment)

## Subtasks 

- [ ] Integrate feedback
- [ ] Extend the tutorial with dDTR (technical setup, sample data)
- [ ] Extend the tutorial with possible diacovery services
- [ ] add "the" portal to the tutorial
- [ ] check used keycloak version/configuration
- [ ] create concept for versioning and releases (release cycle sync)
- [ ] Handover to possible expert group <- just as a reminder 
- [ ] Workshop to identify the different topics of the tutorial. Right now its focused on Data Provider, but we should also think about APP Provider, Operation Companies

## Notes

There is already a small tutorial team, but it might be the case, we need also input from other teams/services.

**Comment by stephanbcbauer** [comment]
Note from open planning ⇾ What is the difference between kits and tutorials. Should be documented somewhere. What is the focus .

**Comment by stephanbcbauer** [comment]
Hello @stephanbcbauer  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @stephanbcbauer ,
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Backlog`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by stephanbcbauer** [comment]
We moved to a subset of this requested functionality. The tutorial was adapted and will be updated via this PR https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/885

**Comment by stephanbcbauer** [comment]
Only one part was done. "The switch from MXD tu Umbrella Helm Charts" with this PR https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/885.

Right now there is no expert group or responsible group for the tutorial
