### ISSUE TITLE
R24.03 Catena-X Portal - Release Checks

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#499]
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.

**Version to be included in Eclipse Tractus-X release**: 1.8.0

**Portal**:
- Portal Chart: [portal-1.8.0](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-1.8.0)
- Portal Frontend: [v1.8.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.8.0)
- Portal Backend: [v1.8.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.8.0)
- Portal Assets: [v1.8.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.8.0)
- Portal Frontend Registration: [v1.6.0](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.6.0)

IAM:
- CentralIdP: [2.1.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-2.1.0)
- SharedIdP: [2.1.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-2.1.0)

**Leading product repository**: https://github.com/eclipse-tractusx/portal

# Compliance Verifications

This issue tracks all compliance related checks, that need to be performed for a product release in Eclipse Tractus-X.

- [x] **Gaia-X** compliance confirmed
- [x] **GDPR** compliance confirmed (personal data, data protection + privacy DPP)
- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed https://github.com/eclipse-tractusx/sig-release/issues/499#issuecomment-1961635593
- [x] Compliant with relevant _published_ **CX Standards** (see the [Catena-X standard library](https://catena-x.net/en/standard-library))

# Documentation

- [x] **Arc24** documentation up-to-date
- [x] **Administrators Guide** up-to-date
- [x] **End-User manual** up-to-date
- [x] **Interface documentation** up-to-date

https://github.com/eclipse-tractusx/sig-release/issues/499#issuecomment-1961635593

# Security Checks

- [x] **Thread Modelling Analysis** passed https://github.com/eclipse-tractusx/sig-security/issues/56
- [x] **Static Application Security Testing** (SAST) scans passed
- [x] **Dynamic Application Security Testing** (DAST) tests passed
- [x] **Secret Scans** passed
- [x] **Software Composition Analysis** (SCA) passed
- [x] **Container Scans** passed
- [x] **Infrastructure as Code** (IaC) scans passed

https://github.com/eclipse-tractusx/sig-release/issues/499#issuecomment-1970832097

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled https://github.com/eclipse-tractusx/portal-cd/issues/203
- [x] Compliant with the **Style Guide**

# Test Results

- [x] **E2E Integration Test** passed https://github.com/eclipse-tractusx/sig-release/issues/499#issuecomment-1948514961
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by evegufy** [comment]
added preliminary release info (version still in release candidate / e2e-testing phase)

**Comment by jjeroch** [comment]
@kelaja please update the status based on the following information:

- ACC "Compliant with the Style Guide" approved. Please update the ticket by clicking on the checkmark below "General Checks"
- Same applies for "User Journey approved" - user journey is approved. I am approving the journey since all user journeys and features are in my ownership. No separate BO existing.
- "GDPR compliance confirmed" - approved as well. The validation as per the previous releases is still valid. Reason: we had already the highest GDPR impact and coverage was approved by the GDPR validation team 


Ongoing:
- Data Sovereignty
- Gaia-X

**Comment by wjost** [comment]
As agreed for R24.3 nothing will be changed. CX is still sticking to pre targus release. I confirm this solution is still GX compliant.

**Comment by ThomasObermeyer** [comment]
Interoperability check has already been done in last release; still valid - since there are no major architecture changes.

**Comment by evegufy** [comment]
@guenterban @RoKrish14 could you please perform the security checks?

**Comment by szymonkowalczykzf** [comment]
Security Assessment Process (Threat Modeling Analysis) approved.

Re-assessment was done on Tuesday 13th Feb 2024. No open findings remains.
Documentation of the assessment will be updated in the Portal docs repo soon.

**Comment by BANANAS1337** [comment]
SCA: Approved
SAST: Approved

**Comment by evegufy** [comment]
> @guenterban @RoKrish14 could you please perform the security checks?

Please check the following scans or tools:

- SAST --> Veracode
- DAST --> Invicti
- Secret Scans --> Gitguardian
- SCA --> Snyk
- Container Scans --> Trivy
- Infrastructure as Code (IaC) --> KICS

And please let me know if you need additional information.
I've checked and as your anyway checking the state yourself, I'm not very keen on posting here screenshots of the security scans.

**Comment by RoKrish14** [comment]
DAST: **Approved**
Secret Scans : **Approved**
Infrastructure as Code (IaC): **Approved**

**Comment by vialkoje** [comment]
could you please add the links to the documentation documents to check ? 

Arc24 documentation 
Administrators Guide 
End-User manual 
Interface documentation

**Comment by DirkBTSI** [comment]
INT test not performed/not documented.
E2E test performed/documented.
Three (3) high defect.
TM not approved

**Comment by jjeroch** [comment]
> could you please add the links to the documentation documents to check ?
> 
> Arc24 documentation Administrators Guide End-User manual Interface documentation

@vialkoje  we shared those last week wednesday via mail

 
```
System Docu
https://github.com/catenax-ng/tx-portal-assets/tree/main/docs
 
Helm Chart Docu
https://github.com/eclipse-tractusx/portal-cd/blob/main/charts/portal/README.md
 
Ticket in welchem du bitte schriftlich ein „ok“ dalassen musst.
https://github.com/eclipse-tractusx/sig-release/issues/499
 
 
```

**Comment by jjeroch** [comment]
Data Sovereignty checks performed - successful

**Comment by RolaH1t** [comment]
> Compliant with relevant published CX Standards => **agreed**

thx

**Comment by RolaH1t** [comment]
> Data Sovereignty checks performed - successful

can you pls add any evidence (like screenshot etc)?!

**Comment by RolaH1t** [comment]
Data Sovereignty
4x Documentation
SEC: Container Scans
TRGs (due to final version)
Test Mgmt approval pending closure of final test cases. Code update expected => therefore SEC scans need to be re-confirmed based on final code version.
QG approval postponed.

**Comment by RoKrish14** [comment]
Container Scans: **Approved**

**Comment by vialkoje** [comment]
Documentation existing and looking consistent. No specific sovereignty requirements for 24.03 expert approval granted. Please add links to docs to the ticket next time and consider QGate criteria sovereignty for 24.05 !

**Comment by evegufy** [comment]
@SebastianBezold @FaGru3n could you please check the TRGs?

**Comment by evegufy** [comment]
@RoKrish14 could you please perform the security checks again?:

- SAST --> Veracode
- DAST --> Invicti
- Secret Scans --> Gitguardian
- SCA --> Veracode, Snyk
- Container Scans --> Trivy
- Infrastructure as Code (IaC) --> KICS

Just ping once you want you check the security tab. Thank you!

**Comment by RoKrish14** [comment]
Following re-request from @evegufy :

SCA: Approved
SAST: Approved
Secret Scans: Approved
DAST: Approved
Container Scans: Approved
IAC: Approved

**Comment by RolaH1t** [comment]
@SebastianBezold with @FaGru3n on vacation this week, pls prioritize the completion of this TRG issue by 06-Mar latest,
as we are approaching the March Release milestone on Friday.
Thx, Roland

**Comment by SebastianBezold** [comment]
Hi @RolaH1t,

the TRG checks are done. There is one issue, violating a TRG. See eclipse-tractusx/portal#207. The team does not want to fix it for this release. See the [specific issue comment](https://github.com/eclipse-tractusx/portal/issues/207#issuecomment-1978319648) So i'll close the TRG QG issue from my side and leave it up to you to decide, if it has to be fixed or if it can wait for next release

**Comment by evegufy** [comment]
Hi @RolaH1t see [clarification](https://github.com/eclipse-tractusx/portal/issues/207#issuecomment-1980300515), severity-wise this is not at all a topic with needs to be forced into the release.

**Comment by evegufy** [comment]
@Siegfriedk for writing the changelog: those are the final released versions for 24.03:

## Final 24.03 versions

### Portal

Portal Chart: [portal-1.8.0](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-1.8.0)

Portal Frontend: [v1.8.0](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.8.0)

Portal Backend: [v1.8.0](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.8.0)

Portal Assets: [v1.8.0](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.8.0)

Portal Frontend Registration: [v1.6.0](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.6.0)

### IAM

CentralIdP: [centralidp-2.1.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-2.1.0)

SharedIdP: [sharedidp-2.1.0](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-2.1.0)

**Comment by RolaH1t** [comment]
all pre-conditions fulfilled => QG approval granted!
Congrats ;-)
