### ISSUE TITLE
Enhancement Keycloak seeding job to seed variables and secrets

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#578]
## Description

The IAM seeding job is enhanced to include secrets and variables.

## Tasks

- [x] Enhance IDP seeding jobs to include secrets and variables
  - [x] https://github.com/eclipse-tractusx/portal-backend/issues/438
  - [x] https://github.com/eclipse-tractusx/portal-iam/issues/86

## Benefits

- Easier application maintenance
- Improved security with the with management of secrets and variables via seeding job

**Comment by stephanbcbauer** [comment]
Hello @jjeroch , @evegufy 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by jjeroch** [comment]
**Update**
Moved to 24.12.
Likely the ticket still might have some items which might delay further to 24.12.

**Status**
Implementation started; but without releasing any functions so far.

**Comment by evegufy** [comment]
Committers:
@evegufy 
@Phil91 
@ntruchsess 
@oyo

**Comment by evegufy** [comment]
I'm moving the following part into a separate sig-release issue for 25.03:

> Move IAM seeding job from portal backend repo to IAM repo
>  https://github.com/eclipse-tractusx/portal-backend/issues/611
>  https://github.com/eclipse-tractusx/portal-iam/issues/88
>  https://github.com/eclipse-tractusx/portal-iam/issues/87
