### ISSUE TITLE
[PURIS] KIT Release 24.08

### ISSUE THREAD

**Issue by PhillipNalesny** [eclipse-tractusx/sig-release#597]
## Description

The Kit Release 2408 feature encompasses three distinct work packages aimed at enhancing the capabilities and visibility of PURIS and associated standards.

## Overall Impact

Collectively, these three work packages provide added value by ensuring that potential users and stakeholders gain a comprehensive understanding of PURIS and its associated benefits. They will learn how PURIS functions, how to implement it, and how to operate it effectively, thereby maximizing the utility of the platform within their respective domains.

New KIT for Supply Chain Disruption Notification
- Demand and Capacity KIT might want to link to it. 
- Same for PURIS overall KIT.

### Work Package 1: Extension of PURIS Kit with Days of Supply Standard

This work package involves expanding the existing PURIS Kit to incorporate the Days of Supply standard. This includes adjustments to both the Adoption View and Development View of the current PURIS Kit to seamlessly integrate the Days of Supply standard.

### Work Package 2: Upgrade of PURIS Kit

The second work package focuses on upgrading the PURIS Kit by developing and releasing additional content to enhance understanding for target audiences. This may include creating a User Journey or calculating a Business Case to estimate the financial benefits of using PURIS.

### Work Package 3: Creation of Supply Chain Disruption Notification Kit

The third work package entails the creation of a completely new kit, the Supply Chain Disruption Notification Kit. This kit will feature the standard "Supply Chain Disruption Notification", scheduled for release 2405, in collaboration with Team DCM. The aim is to make the standard accessible and understandable to a wide audience. The creation of the Adoption View, Development View, and Operations View will be carried out by the PURIS team. Team DCM, which collaborated with PURIS in creating the standard, will review the kit and provide feedback for incorporation by PURIS.

## Acceptance Criteria:

- [ ] Days of Supply Standard is implemented in PURIS KIT
- [ ] PURIS KIT is updated with regards to a described scenario, user journey, business case
- [ ] Supply Chain DIsruption Notification KIT is created

Committer in charge: @tom-rm-meyer-ISST

**Comment by stephanbcbauer** [comment]
Was presented in open planning ⇾ contributors and committer are involved.

**Comment by stephanbcbauer** [comment]
Hello @MercedesG-8020 , @tom-rm-meyer-ISST  @PhillipNalesny ,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by PhillipNalesny** [comment]
Thanks @stephanbcbauer , Feature in progress, Here is our planning board on it https://github.com/orgs/eclipse-tractusx/projects/58/views/1

**Comment by stephanbcbauer** [comment]
Hello @PhillipNalesny 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by tom-rm-meyer-ISST** [comment]
@stephanbcbauer the KITs are on track. We're currently finishing them and will create the initial pull request via a supporter of ours :)

**Comment by tom-rm-meyer-ISST** [comment]
This will be solved by #787 and #784

**Comment by matbmoser** [comment]
PURIS KIT pr is closed!

**Comment by tom-rm-meyer-ISST** [comment]
Solved with https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/986
