### ISSUE TITLE
[DCM-KIT] Onboarding Video

### ISSUE THREAD

**Issue by MWADCM** [eclipse-tractusx/sig-release#607]
## Description

Introduce an DCM Onboarding Video to be able to have an easy access to the DCM Use Case, especially for new adopters. This will support an initial and better understanding and adaption of DCM in a few minutes (similar to the Catena-X video on the Catena-X Homepage).
Important: There are currently licensing issues for the development of an onboarding video. 
The current risk is that the timeline for 24/08 is not met and that, if necessary, only an interim result of an onboarding video can be handed over. 
Update @MWADCM Risk is valid. Will not be finished by Rel. 24/08 

## Impact
Easier access to the DCM use case making the whole idea more touchable especially for new potential adopters who have not read any other DCM content yet. On top the target is to catch the attention of visitors of the DCM KIT without forcing them to read and click through many documents.

## Tasks
- [ ] Solving license issues concerning Video content/software
- [ ] Formal Handover of individual topics from DCM Consortia Group
- [ ] Expert Group internal alignment and understanding on Consortia Group handover topics
- [ ] Final Preparation of DCM Onboarding (Video) content for DCM KIT
- [ ] Initial Pull Request GITHUB until 11.07.2024
- [ ] Final Pull Request GITHUB until 25.07.2024
- [ ] Publication in DCM KIT on Tractus-X 08/24

**Comment by stephanbcbauer** [comment]
Was presented in open planning ⇾ contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @MWADCM ,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by MWADCM** [comment]
Update @MWADCM Risk is valid. Will not be finished by Rel. 24/08

**Comment by stephanbcbauer** [comment]
@Grand-Thibault  This was a feature for milestone 24.08. It has the status NOT in Release, which is OK, but is planned with this feature? 24.12? 25.03?

**Comment by Grand-Thibault** [comment]
@MWADCM @LukasSchmetz see Stephans comment above

**Comment by LukasSchmetz** [comment]
@stephanbcbauer Now further work on this feature planned currently. Therefore we put it on "Not in Release" as there was on close option.

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
