### ISSUE TITLE
Include Digital Twin Registry in Tractus-X Tutorial

### ISSUE THREAD

**Issue by thomas-henn** [eclipse-tractusx/sig-release#634]
### Description
______
Add tutorial description to https://eclipse-tractusx.github.io/docs/tutorials
especially for https://eclipse-tractusx.github.io/docs/tutorials/e2e/connect/deployComponents
for the use of the Tractus-X Digital Twin Registry as data asset in the EDC.
EDC tutorial is already available.

Also see https://github.com/eclipse-tractusx/sig-release/issues/430

### Subtasks
______

- [x] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/380
- [x] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/381
- [x] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/382
- [x] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/383

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ developer and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @thomas-henn 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @tunacicek, @agg3fe 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by tunacicek** [comment]
Hi @stephanbcbauer ,
state is set to done.
