### ISSUE TITLE
Create Concept for History of Digital Twins

### ISSUE THREAD

**Issue by thomas-henn** [eclipse-tractusx/sig-release#635]
### Description
-----------
Digital Twins currently do not have any timestamps for the CRUD operations on different data fields.
Especially for the /lookup-API and /shellsByAssetLink-API filtering for the most recent shells is requested.

Alignment with IDTA on AAS-APIs is needed.

And concept on reference implementation is needed.

### Subtasks
-----------

- [ ] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/385
- [ ] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/386
- [ ] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/387
- [ ] https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/388

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ its a conecept right now

**Comment by stephanbcbauer** [comment]
Hello @thomas-henn 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by RazvanZmau** [comment]
The decision is to obsolete for now.
