### ISSUE TITLE
[DPP]  Digital Product Pass Verification Documentation Update (R24.08)

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-release#651]
## Description
The Digital Product Pass Verification Documentation released in the `R24.05` was the first version release of the verification concept, however some parts are incomplete, and it's missing details from the implementation done in the PoC that will be released in the `R24.08`.

Documentation link: https://github.com/eclipse-tractusx/digital-product-pass/tree/docs/verification/dpp-verification

## Objectives
- [X] Link documentation in the Eco Pass KIT.
     - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/952
- [X] Revise the `v1.0` of the Verification Concept and identify improvements
- [ ] Update documentation with new Diagrams
- [ ] Complete unfinished sections with detailed explanations

## Impact
- Give guideline on how to create Verification Statements for any aspect model, helping for example the PCF Verification and other models in the Industry Core.
- Link the `dpp-verification` documentation in the Eco Pass KIT.

## Dependencies
- No dependencies to other products
- Eco Pass KIT dependency

### Added in EcoPass KIT the link to the digital product pass verification.
Now in the EcoPass Kit is available the link for the documentation, with a basic explanation of the context.

### Updated documentation with Diagrams
The documentation regarding digital product pass verification was outdated after the implementation took place. The fore new context diagrams were designed to explain the context and the necessary steps for verifying data. 

### New schemas and information about models
Included a section on how to create the digital product pass certified data credentials, also provided guidelines on how to certify and verify data in Catena-X.

## Additional information 

- [X] The documentation work will be done in the consortia phase v24.05 and implemented for v24.08
- [X] I am willing to contribute to this feature.

### Tasks

- [X] Perform revision of the content and identify spots where information is missing
- [ ] Update this documentation https://github.com/eclipse-tractusx/digital-product-pass/tree/main/dpp-verification:
    - [ ] Add details from implementation (refine the diagrams)
    - [x] Add schemas for each verifiable credentials
    - [x] Correct identified typos
- [x] Place reference to docs in the Eco Pass KIT under development view

### Commiters
- @matbmoser

### Related Issues
- https://github.com/eclipse-tractusx/sig-release/issues/655

### Related PRs
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/952
- https://github.com/eclipse-tractusx/digital-product-pass/pull/369

**Comment by stephanbcbauer** [comment]
Hello @matbmoser , @saudkhan116 ,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by matbmoser** [comment]
No whitepaper will be published by the expert group, the content from the final documentation will be uploaded until the end of june.

**Comment by matbmoser** [comment]
I have placed the note in the Eco Pass KIT, for the sake of not duplicating information I have placed just a link.

https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/952

**Comment by stephanbcbauer** [comment]
Hello @matbmoser, 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by matbmoser** [comment]
Latest status: updating the documentation from the verification

**Comment by matbmoser** [comment]
@stephanbcbauer updated the status and description from this feature. Its still open since the PRs are open, the documentation is still being updated, and will be merged by the end of the week. The development is already finished last week when the first release candidate was released: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.0-rc1

**Comment by matbmoser** [comment]
Documentation updated and published in the release v4.0.0 https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.0

We even have a github site:
https://eclipse-tractusx.github.io/digital-product-pass/dpp-verification/
