### ISSUE TITLE
[DPP] Update to latest models and implement check for plausability with json schema

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-release#654]
## Description
The problem with the Digital Product Pass application is that we are limited to the following deprecated models:
- Digital Product Pass v2.0.0
- Battery Pass 3.0.1
- Transmission Pass 1.0.0

We need to update it to the latest models:

- Digital Product Pass v5.0.0
- Battery Pass 6.0.0
- Transmission Pass 3.0.0

If there is time left this will be integrated:

The generic digital product passport aspect is the base for the future for all the other CX use case specific passports based on the Digital Product Passport. Therefore based on its version we can visualize the generic data from the passport in the ui.

In the future in the DPP Expert Group there will be more versions and corrections for the data models in the digital product pass use case. And this models will be incompatible with the Application. Therefore there is the need to visualize any aspect model version based on its modelling schema. This schemas are uploaded to the semantichub and available to be parsed by the digital product pass backend.

The idea is to use the structure provide in the Digital Product Pass aspect model in the section of "additionalData" which provides a infinite generic json structure that can be mapped

## Tasks
- [X] Create an algorithm to convert any catena-x payload into generic format @matbmoser 
- [x] Latest models working (https://github.com/eclipse-tractusx/digital-product-pass/issues/270) (IN TESTING)  @davidzynda 

## Additional information 
- [X] I'm willing to contribute to this feature
- [X] Will be developed in consortia to be released by association in DPP Expert Group

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ responsible committers are already defined

**Comment by matbmoser** [comment]
Added this ticket: https://github.com/eclipse-tractusx/digital-product-pass/issues/261
Since it will not be included in the release 24.05 because it can not be tested with the latest BDPM which is not available (1 week before QG Check) it will be just included in the next release with the Generic UI feature.

**Comment by stephanbcbauer** [comment]
Hello @davidzynda , @saudkhan116 ,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by saudkhan116** [comment]
We are currently integrating and checking support for the latest models versions https://github.com/eclipse-tractusx/digital-product-pass/issues/270

**Comment by matbmoser** [comment]
Updating the status here: we will not integrate with the BPDM service, generic UI will include the new models visualization (latest standardized ones in v24.08): 
 - DPP 5.0.0
 - BPP 6.0.0
 -Transmission Pass 3.0.0

If we can not include the visualization of any model that is based on the DPP it will not be included and will just be added as an add-on.

**Comment by matbmoser** [comment]
Status update:

- @saudkhan116  and me were looking and trying to get it integrated as we planned, however its unfortunate but we can't get the "prefferedName" and description of every single attribute in the semantic hub ttl file... So the generic Ui will not be implemented at all because it is not possible. At least we have arrived in the bottom.
- @davidzynda will integrate the latest models.
- @saudkhan116 will create a semantic parser getting the schema from semantic hub

**Comment by matbmoser** [comment]
Models are updated and working.

**Comment by matbmoser** [comment]
Closing this issue since its already release in v3.1.0: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v3.1.0

**Comment by matbmoser** [comment]
Closing this issue since its already release in v3.1.0: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v3.1.0

**Comment by matbmoser** [comment]
@stephanbcbauer Updated the description and refined the what was implemented in this feature
