### ISSUE TITLE
[DPP] Implementation of Digital Product Pass Verification Concept released in v24.05 

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-release#655]
## Description
The Digital Product Pass Verification is a work in progress add-on that is being done at the end of consortia phase.

The documentation that will be published in the release R24.05 https://github.com/eclipse-tractusx/digital-product-pass/issues/264 will explain how the concept for documentation is done. Additionally in #651 will be published the whitepaper containing the exact details on how to do the verification and certification.

The discussions with the architects are already ongoing, the first approval was received from Core-ART platform capability, but the exact details on how will can be implemented will be still defined in the R24.05 Documentation which will be published in the consortia. 

In resume using the wallet we can sign/certify and verify documents. 
Additionally we check for Data Plausability against the SemanticModels.

## Impact

- Using the a wallet we will be able to certify and verify aspect model documents, like the digital product pass.
- The application will be able to communicate and do this functionality.
- Make a maven package for the verification

## Additional information 

- [x] I'm willing to contribute to this feature
- [x] This work will be done in consortia time and will be also connected with the DPP Expert Group discussions

Link to documentation: https://github.com/eclipse-tractusx/digital-product-pass/tree/main/dpp-verification 

### Tasks

- [X] Generate test data from real semantic models 
- [X] Create jsonld schemas for Verifiable Credentials and semantic models (Hardest part)
- [x] Sign a Verifiable Credential with a wallet (Having just a problem with the private key generation)
- [x] Make verifiable credential available in a digital twin
- [x] Implement logic in backend to get the verifiable credential
- [x] Implement logic in frontend to show it is verified
- [x] Documentation updated in kit #651

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ responsible committers are already defined

**Comment by matbmoser** [comment]
Ok I am starting to work on this ticket since yesterday. First challenge, make a "valid" CDC and CSC json-ld credentials based on info from semantic hub.

**Comment by matbmoser** [comment]
Using the schema file we are able to generate this view: 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/dddd361a-0c4f-4d73-9f10-1ee62577c8a0)
 where the schema context can reference to

**Comment by matbmoser** [comment]
![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/959a66f1-77e2-4129-b6ea-c8fa0451b26a)

**Comment by matbmoser** [comment]
I have just created an amazing thing:


![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/825f7d09-8c80-4344-a74a-9a1a25a77ba1)

This python function uses "recursion" to generate a JSON-LD context from a json schema from **ANY!** Catena-X Aspect model:
Example with bom as build:

<details>

<summary>Collapse this to see the REQUEST</summary>
```json

{
    "semanticId": "urn:samm:io.catenax.single_level_bom_as_built:3.0.0#",
    "schema": {
    "$schema" : "http://json-schema.org/draft-04/schema",
    "description" : "The single-level bill of material represents one sub-level of an assembly and does not include any lower-level subassemblies. The as-built lifecycle references all child items as manufactured by the manufacturer referencing only child items in an as-built lifecycle themselves (e.g. serial parts or batches), unless parts can only be tracked by an part ID (on a type level).\n\nIf it is unclear which item has been built-in into the parent item, all potential parts must be listed. This is the case when, e.g. the same item is supplied by two suppliers and the item is only tracked by a customer part ID during assembly, these items can not be differentiated from each other.\n",
    "type" : "object",
    "components" : {
      "schemas" : {
        "urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait" : {
          "type" : "string",
          "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
          "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
        },
        "urn_samm_io.catenax.single_level_bom_as_built_3.0.0_DateTimeTrait" : {
          "type" : "string",
          "description" : "Regular Expression to enable UTC and Timezone formats and the possibility to exclude time information.",
          "pattern" : "^-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])(T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?)?$"
        },
        "urn_samm_io.catenax.shared.quantity_2.0.0_QuantityValueCharacteristic" : {
          "type" : "number",
          "description" : "The quantity value associated with the unit expressed as float."
        },
        "urn_samm_io.catenax.shared.quantity_2.0.0_ItemUnitEnumeration" : {
          "type" : "string",
          "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
          "description" : "Enumeration for common item units.",
          "enum" : [ "unit:piece", "unit:set", "unit:pair", "unit:page", "unit:cycle", "unit:kilowattHour", "unit:gram", "unit:kilogram", "unit:tonneMetricTon", "unit:tonUsOrShortTonUkorus", "unit:ounceAvoirdupois", "unit:pound", "unit:metre", "unit:centimetre", "unit:kilometre", "unit:inch", "unit:foot", "unit:yard", "unit:squareCentimetre", "unit:squareMetre", "unit:squareInch", "unit:squareFoot", "unit:squareYard", "unit:cubicCentimetre", "unit:cubicMetre", "unit:cubicInch", "unit:cubicFoot", "unit:cubicYard", "unit:litre", "unit:millilitre", "unit:hectolitre", "unit:secondUnitOfTime", "unit:minuteUnitOfTime", "unit:hourUnitOfTime", "unit:day" ]
        },
        "urn_samm_io.catenax.shared.quantity_2.0.0_ItemQuantityCharacteristic" : {
          "description" : "Characteristic for measurements of an item (mass, count, linear, area, volume, misc).",
          "type" : "object",
          "properties" : {
            "value" : {
              "description" : "The quantity value associated with the unit.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_QuantityValueCharacteristic"
            },
            "unit" : {
              "description" : "The unit of an item. Common units may be related to mass, count, linear, area, volume or misc.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_ItemUnitEnumeration"
            }
          },
          "required" : [ "value", "unit" ]
        },
        "urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait" : {
          "type" : "string",
          "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two alphanumeric letters.",
          "pattern" : "^BPNL[a-zA-Z0-9]{12}$"
        },
        "urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean" : {
          "type" : "boolean",
          "description" : "Represents a boolean value (i.e. a \"flag\")."
        },
        "urn_samm_io.catenax.single_level_bom_as_built_3.0.0_ChildData" : {
          "description" : "Catena-X ID and meta data of the assembled child item.",
          "type" : "object",
          "properties" : {
            "createdOn" : {
              "description" : "Timestamp when the relation between the parent item and the child item was created, e.g. when the serialized child part was assembled into the given part.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.single_level_bom_as_built_3.0.0_DateTimeTrait"
            },
            "quantity" : {
              "description" : "Quantity of which the child item is assembled into the parent item. In general it is '1' for serialized parts.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_ItemQuantityCharacteristic"
            },
            "lastModifiedOn" : {
              "description" : "Timestamp when the assembly relationship between parent item and child item was last modified.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.single_level_bom_as_built_3.0.0_DateTimeTrait"
            },
            "businessPartner" : {
              "description" : "The supplier of the given child item.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait"
            },
            "hasAlternatives" : {
              "description" : "Expresses whether the part is built-in or wether it is one of several options. If the value is false, it can be assumed this exact item is built-in. If the value is true, it is unknown wether this or an alternative item is built-in.\nThis is the case when, e.g. the same item is supplied by two suppliers, the item is only tracked by a customer part ID during assembly. Thus, these items can not be differentiated from each other.\n\n",
              "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean"
            },
            "catenaXId" : {
              "description" : "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace.",
              "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait"
            }
          },
          "required" : [ "createdOn", "quantity", "businessPartner", "hasAlternatives", "catenaXId" ]
        },
        "urn_samm_io.catenax.single_level_bom_as_built_3.0.0_SetOfChildItemsCharacteristic" : {
          "description" : "Set of child items the parent item was assembled by (one structural level down).",
          "type" : "array",
          "items" : {
            "$ref" : "#/components/schemas/urn_samm_io.catenax.single_level_bom_as_built_3.0.0_ChildData"
          },
          "uniqueItems" : true
        }
      }
    },
    "properties" : {
      "catenaXId" : {
        "description" : "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace.",
        "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait"
      },
      "childItems" : {
        "description" : "Set of child items, of which the given parent item was assembled by (one structural level down).",
        "$ref" : "#/components/schemas/urn_samm_io.catenax.single_level_bom_as_built_3.0.0_SetOfChildItemsCharacteristic"
      }
    },
    "required" : [ "catenaXId", "childItems" ]
  }
}
```
</details>

And this is produced:

<details>

<summary>Collapse this to see the RESPONSE</summary>
```json
{
    "@context": {
        "@version": 1.1,
        "catenaXId": {
            "@definition": "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace.",
            "@type": "schema:string"
        },
        "childItems": {
            "@container": "@list",
            "@context": {
                "@context": {
                    "@version": 1.1,
                    "businessPartner": {
                        "@definition": "The supplier of the given child item.",
                        "@type": "schema:string"
                    },
                    "catenaXId": {
                        "@definition": "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace.",
                        "@type": "schema:string"
                    },
                    "createdOn": {
                        "@definition": "Timestamp when the relation between the parent item and the child item was created, e.g. when the serialized child part was assembled into the given part.",
                        "@type": "schema:string"
                    },
                    "hasAlternatives": {
                        "@definition": "Expresses whether the part is built-in or wether it is one of several options. If the value is false, it can be assumed this exact item is built-in. If the value is true, it is unknown wether this or an alternative item is built-in.\nThis is the case when, e.g. the same item is supplied by two suppliers, the item is only tracked by a customer part ID during assembly. Thus, these items can not be differentiated from each other.\n\n",
                        "@type": "schema:boolean"
                    },
                    "id": "@id",
                    "lastModifiedOn": {
                        "@definition": "Timestamp when the assembly relationship between parent item and child item was last modified.",
                        "@type": "schema:string"
                    },
                    "quantity": {
                        "@context": {
                            "@version": 1.1,
                            "id": "@id",
                            "type": "@type",
                            "unit": {
                                "@definition": "The unit of an item. Common units may be related to mass, count, linear, area, volume or misc.",
                                "@type": "schema:string"
                            },
                            "value": {
                                "@definition": "The quantity value associated with the unit.",
                                "@type": "schema:number"
                            }
                        },
                        "@definition": "Quantity of which the child item is assembled into the parent item. In general it is '1' for serialized parts."
                    },
                    "type": "@type"
                },
                "@definition": "Catena-X ID and meta data of the assembled child item."
            },
            "@definition": "Set of child items, of which the given parent item was assembled by (one structural level down)."
        },
        "id": "@id",
        "type": "@type"
    },
    "@definition": "The single-level bill of material represents one sub-level of an assembly and does not include any lower-level subassemblies. The as-built lifecycle references all child items as manufactured by the manufacturer referencing only child items in an as-built lifecycle themselves (e.g. serial parts or batches), unless parts can only be tracked by an part ID (on a type level).\n\nIf it is unclear which item has been built-in into the parent item, all potential parts must be listed. This is the case when, e.g. the same item is supplied by two suppliers and the item is only tracked by a customer part ID during assembly, these items can not be differentiated from each other.\n",
    "aspect": "urn:samm:io.catenax.single_level_bom_as_built:3.0.0#",
    "schema": "https://schema.org/"
}
```

**Comment by matbmoser** [comment]
And this is produced:

<details>

<summary>Collapse this to see the RESPONSE</summary>

```json
{
    "@context": {
        "@version": 1.1,
        "catenaXId": {
            "@definition": "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace.",
            "@type": "schema:string"
        },
        "childItems": {
            "@container": "@list",
            "@context": {
                "@context": {
                    "@version": 1.1,
                    "businessPartner": {
                        "@definition": "The supplier of the given child item.",
                        "@type": "schema:string"
                    },
                    "catenaXId": {
                        "@definition": "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace.",
                        "@type": "schema:string"
                    },
                    "createdOn": {
                        "@definition": "Timestamp when the relation between the parent item and the child item was created, e.g. when the serialized child part was assembled into the given part.",
                        "@type": "schema:string"
                    },
                    "hasAlternatives": {
                        "@definition": "Expresses whether the part is built-in or wether it is one of several options. If the value is false, it can be assumed this exact item is built-in. If the value is true, it is unknown wether this or an alternative item is built-in.\nThis is the case when, e.g. the same item is supplied by two suppliers, the item is only tracked by a customer part ID during assembly. Thus, these items can not be differentiated from each other.\n\n",
                        "@type": "schema:boolean"
                    },
                    "id": "@id",
                    "lastModifiedOn": {
                        "@definition": "Timestamp when the assembly relationship between parent item and child item was last modified.",
                        "@type": "schema:string"
                    },
                    "quantity": {
                        "@context": {
                            "@version": 1.1,
                            "id": "@id",
                            "type": "@type",
                            "unit": {
                                "@definition": "The unit of an item. Common units may be related to mass, count, linear, area, volume or misc.",
                                "@type": "schema:string"
                            },
                            "value": {
                                "@definition": "The quantity value associated with the unit.",
                                "@type": "schema:number"
                            }
                        },
                        "@definition": "Quantity of which the child item is assembled into the parent item. In general it is '1' for serialized parts."
                    },
                    "type": "@type"
                },
                "@definition": "Catena-X ID and meta data of the assembled child item."
            },
            "@definition": "Set of child items, of which the given parent item was assembled by (one structural level down)."
        },
        "id": "@id",
        "type": "@type"
    },
    "@definition": "The single-level bill of material represents one sub-level of an assembly and does not include any lower-level subassemblies. The as-built lifecycle references all child items as manufactured by the manufacturer referencing only child items in an as-built lifecycle themselves (e.g. serial parts or batches), unless parts can only be tracked by an part ID (on a type level).\n\nIf it is unclear which item has been built-in into the parent item, all potential parts must be listed. This is the case when, e.g. the same item is supplied by two suppliers and the item is only tracked by a customer part ID during assembly, these items can not be differentiated from each other.\n",
    "aspect": "urn:samm:io.catenax.single_level_bom_as_built:3.0.0#",
    "schema": "https://schema.org/"
}
```
</details>

**Comment by matbmoser** [comment]
I present the first valid JSON-LD credential for Catena-X built in a generic way for any data model:

```json

{
    "id": "https://tx-dpp.int.demo.catena-x.net/provider_backend/data/cx:mfg024:prt-30001",
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3c.github.io/vc-jws-2020/contexts/v1",
        {
            "@context": {
                "@version": 1.1,
                "catenaXId": {
                    "@context": {
                        "@definition": "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace."
                    },
                    "@id": "aspect:catenaXId",
                    "@type": "schema:string"
                },
                "childItems": {
                    "@container": "@list",
                    "@context": {
                        "@context": {
                            "@version": 1.1,
                            "businessPartner": {
                                "@context": {
                                    "@definition": "The supplier of the given child item."
                                },
                                "@id": "aspect:businessPartner",
                                "@type": "schema:string"
                            },
                            "catenaXId": {
                                "@context": {
                                    "@definition": "The Catena-X ID of the given part (e.g. the component), valid for the Catena-X dataspace."
                                },
                                "@id": "aspect:catenaXId",
                                "@type": "schema:string"
                            },
                            "createdOn": {
                                "@context": {
                                    "@definition": "Timestamp when the relation between the parent item and the child item was created, e.g. when the serialized child part was assembled into the given part."
                                },
                                "@id": "aspect:createdOn",
                                "@type": "schema:string"
                            },
                            "hasAlternatives": {
                                "@context": {
                                    "@definition": "Expresses whether the part is built-in or wether it is one of several options. If the value is false, it can be assumed this exact item is built-in. If the value is true, it is unknown wether this or an alternative item is built-in.\nThis is the case when, e.g. the same item is supplied by two suppliers, the item is only tracked by a customer part ID during assembly. Thus, these items can not be differentiated from each other.\n\n"
                                },
                                "@id": "aspect:hasAlternatives",
                                "@type": "schema:boolean"
                            },
                            "id": "@id",
                            "lastModifiedOn": {
                                "@context": {
                                    "@definition": "Timestamp when the assembly relationship between parent item and child item was last modified."
                                },
                                "@id": "aspect:lastModifiedOn",
                                "@type": "schema:string"
                            },
                            "quantity": {
                                "@context": {
                                    "@definition": "Quantity of which the child item is assembled into the parent item. In general it is '1' for serialized parts.",
                                    "@version": 1.1,
                                    "id": "@id",
                                    "type": "@type",
                                    "unit": {
                                        "@context": {
                                            "@definition": "The unit of an item. Common units may be related to mass, count, linear, area, volume or misc."
                                        },
                                        "@id": "aspect:unit",
                                        "@type": "schema:string"
                                    },
                                    "value": {
                                        "@context": {
                                            "@definition": "The quantity value associated with the unit."
                                        },
                                        "@id": "aspect:value",
                                        "@type": "schema:number"
                                    }
                                },
                                "@id": "aspect:quantity"
                            },
                            "type": "@type"
                        },
                        "@definition": "Set of child items, of which the given parent item was assembled by (one structural level down).",
                        "@version": 1.1,
                        "id": "@id",
                        "type": "@type"
                    },
                    "@id": "aspect:childItems"
                },
                "id": "@id",
                "type": "@type"
            },
            "@id": "SingleLevelBomAsBuilt",
            "aspect": "urn:samm:io.catenax.single_level_bom_as_built:3.0.0#",
            "schema": "https://schema.org/"
        }
    ],
    "type": [
        "VerifiableCredential",
        "CDC",
        "DPP"
    ],
    "issuer": "did:web:wallet-url.test.com:BPNL00000007RVTB",
    "parent": {
        "@id": "did:web:dpp-test-system.com:BPNL000000000000:api:public:urn%3Auuid%3A1c5b6a7c-90d4-3481-0538-f134ff53076d",
        "checksum": "64b1a523da600e8fc0018cf57b8f7756b83bb6e9b11c81b1c7444272fab239902321b1b6ae6624d6846fd010616ae98c118f12491f922badd64e58b782c6a115"
    },
    "credentialSubject": {
        "catenaXId": "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
        "childItems": [
            {
                "catenaXId": "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d",
                "quantity": {
                    "value": 20.0,
                    "unit": "unit:piece"
                },
                "hasAlternatives": false,
                "createdOn": "2022-02-03T14:48:54.709Z",
                "businessPartner": "BPNL50096894aNXY",
                "lastModifiedOn": "2022-02-03T14:48:54.709Z"
            }
        ]
    },
    "issuanceDate": "2024-02-15T00:00:00.000Z",
    "proof": {
        "type": "JsonWebSignature2020",
        "created": "2024-02-15T12:35:39Z",
        "verificationMethod": "did:web:wallet-url.test.com:BPNL00000007RVTB#8f858500-7008-4b97-a8bb-605d4c8eca75",
        "proofPurpose": "assertionMethod",
        "jws": "eyJhbGciOiJFZERTQSJ9..4snTkqta4UwXIAtKJiIEDhiwmVtAC3kml0j7Wc25vmTbLbPlviXgL9he9X0A0xRTNlnsEwILf0NbPIyeztzJCw"
    }
}
```


Which can be expanded in this:

<details>

<summary>Click to see the expanded json-ld</summary>
```json
[
    {
      "https://www.w3.org/2018/credentials#credentialSubject": [
        {
          "aspect:catenaXId": [
            {
              "@type": "schema:string",
              "@value": "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d"
            }
          ],
          "aspect:childItems": [
            {
              "@list": [
                {
                  "aspect:businessPartner": [
                    {
                      "@type": "schema:string",
                      "@value": "BPNL50096894aNXY"
                    }
                  ],
                  "aspect:catenaXId": [
                    {
                      "@type": "schema:string",
                      "@value": "urn:uuid:055c1128-0375-47c8-98de-7cf802c3241d"
                    }
                  ],
                  "aspect:createdOn": [
                    {
                      "@type": "schema:string",
                      "@value": "2022-02-03T14:48:54.709Z"
                    }
                  ],
                  "aspect:hasAlternatives": [
                    {
                      "@type": "schema:boolean",
                      "@value": false
                    }
                  ],
                  "aspect:lastModifiedOn": [
                    {
                      "@type": "schema:string",
                      "@value": "2022-02-03T14:48:54.709Z"
                    }
                  ],
                  "aspect:quantity": [
                    {
                      "aspect:unit": [
                        {
                          "@type": "schema:string",
                          "@value": "unit:piece"
                        }
                      ],
                      "aspect:value": [
                        {
                          "@type": "schema:number",
                          "@value": 20
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ],
      "@id": "https://tx-dpp.int.demo.catena-x.net/provider_backend/data/cx:mfg024:prt-30001",
      "https://www.w3.org/2018/credentials#issuanceDate": [
        {
          "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
          "@value": "2024-02-15T00:00:00.000Z"
        }
      ],
      "https://www.w3.org/2018/credentials#issuer": [
        {
          "@id": "did:web:wallet-url.test.com:BPNL00000007RVTB"
        }
      ],
      "https://w3id.org/security#proof": [
        {
          "@graph": [
            {
              "http://purl.org/dc/terms/created": [
                {
                  "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
                  "@value": "2024-02-15T12:35:39Z"
                }
              ],
              "https://w3id.org/security#jws": [
                {
                  "@value": "eyJhbGciOiJFZERTQSJ9..4snTkqta4UwXIAtKJiIEDhiwmVtAC3kml0j7Wc25vmTbLbPlviXgL9he9X0A0xRTNlnsEwILf0NbPIyeztzJCw"
                }
              ],
              "https://w3id.org/security#proofPurpose": [
                {
                  "@id": "https://w3id.org/security#assertionMethod"
                }
              ],
              "@type": [
                "https://w3id.org/security#JsonWebSignature2020"
              ],
              "https://w3id.org/security#verificationMethod": [
                {
                  "@id": "did:web:wallet-url.test.com:BPNL00000007RVTB#8f858500-7008-4b97-a8bb-605d4c8eca75"
                }
              ]
            }
          ]
        }
      ],
      "@type": [
        "https://www.w3.org/2018/credentials#VerifiableCredential",
        "CDC",
        "DPP"
      ]
    }
  ]
```
</details>

**Comment by matbmoser** [comment]
Status here:

- Created first catena-x fully functionally verifiable credential in json ld (Test Data)
- Implementation in backend will be simply call a API for verifying the credentials in a wallet.
- Frontend implementation will just show if the data is verified or not.
- Documentation will be updated and placed in the kit #651 -> After implementation (July)

**Comment by matbmoser** [comment]
For assuring data integrity I will add the checksum form the expanded json-ld in the signature: 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/2e8b24c3-3ec6-47bb-bffc-1ab4beaef765)

**Comment by matbmoser** [comment]
I could finally verify our first credential issued!


![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/e9298a9a-c4c0-47b9-adf5-20e92ffdd6c8)

**Comment by matbmoser** [comment]
Started working in migrating the simple wallet to tractus-x, it was before in my personal repository to test thingshttps://github.com/matbmoser/simple-wallet: 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/0f96073f-cc4b-42ce-bc8b-7e466132f2f2)

Working in the following branch https://github.com/eclipse-tractusx/digital-product-pass/tree/feature/simple-wallet

**Comment by matbmoser** [comment]
I just implemented authorization: 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/6e3739b6-4f2b-4fa0-878d-ce77b0c27634)

Now if the API key is not configured here:


![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/ba211285-de3e-48ca-b782-133287fd9c87)


The application will no accept the requests

**Comment by matbmoser** [comment]
For authentication requests the user needs to add its BPN: 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/f686911b-7258-4c31-b88f-1f7bab607835)

BPN is like the "clientId"
and the API Key the "clientSecret"

**Comment by matbmoser** [comment]
Ok I created a docker container for the wallet 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/c3ec45c2-37ed-4d81-bb69-24fb95d93e67)

**Comment by matbmoser** [comment]
I  have registered the digital twin:

```json
{
    "description": [
        {
            "language": "en",
            "text": "Battery Digital Twin"
        }
    ],
    "displayName": [],
    "globalAssetId": "urn:uuid:a4c600e8-b11f-4e1d-a2f9-80ad518806b8",
    "idShort": "Battery_DPP-XYZ789",
    "id": "urn:uuid:a4c600e8-b11f-4e1d-a2f9-80ad518806b8",
    "specificAssetIds": 
        [
            {
                "name": "digitalTwinType",
                "value": "PartInstance",
                "externalSubjectId": {
                    "type": "ExternalReference",
                    "keys": [
                        {
                            "type": "GlobalReference",
                            "value": "BPNL0073928UJ879"
                        }
                    ]
                }
            },
            {
                "name": "partInstanceId",
                "value": "DPPV-0001",
                "externalSubjectId": {
                    "type": "ExternalReference",
                    "keys": [
                        {
                            "type": "GlobalReference",
                            "value": "BPNL0073928UJ879"
                        }
                    ]
                }
            },
            {
                "name": "manufacturerPartId",
                "value": "MPI7654",
                "externalSubjectId": {
                    "type": "ExternalReference",
                    "keys": [
                        {
                            "type": "GlobalReference",
                            "value": "BPNL0073928UJ879"
                        },
                        {
                            "type": "GlobalReference",
                            "value": "PUBLIC_READABLE"
                        }
                    ]
                }
            },
            {
                "name": "manufacturerId",
                "value": "BPNL0073928UJ879",
                "externalSubjectId": {
                    "type": "ExternalReference",
                    "keys": [
                        {
                            "type": "GlobalReference",
                            "value": "BPNL0073928UJ879"
                        }
                    ]
                }
            }
        ],
    "submodelDescriptors": [
        {
            "endpoints": [
                {
                    "interface": "SUBMODEL-3.0",
                    "protocolInformation": {
                        "href": "https://dpp.int.demo.catena-x.net/BPNL000000000000/api/public/data/urn:uuid:a377ff49-6bde-4215-8d38-b8f02c991a35",
                        "endpointProtocol": "HTTP",
                        "endpointProtocolVersion": [
                            "1.1"
                        ],
                        "subprotocol": "DSP",
                        "subprotocolBody": "id=urn:uuid:3e4a5957-f226-478a-ab18-79ced49d6195;dspEndpoint=https://dpp.int.demo.catena-x.net/BPNL000000000000",
                        "subprotocolBodyEncoding": "plain",
                        "securityAttributes": [
                            {
                                "type": "NONE",
                                "key": "NONE",
                                "value": "NONE"
                            }
                        ]
                    }
                }
            ],
            "idShort": "digitalProductPass",
            "id": "urn:uuid:a377ff49-6bde-4215-8d38-b8f02c991a35",
            "semanticId": {
                "type": "ExternalReference",
                "keys": [
                    {
                        "type": "Entity",
                        "value": "https://www.w3.org/ns/credentials/v2"
                    },
                    {
                        "type": "DataElement",
                        "value": "urn:samm:io.catenax.dpp_verification.cdc:1.0.0#CertifiedDataCredential"
                    },
                    {
                        "type": "Submodel",
                        "value": "urn:samm:io.catenax.generic.digital_product_passport:4.0.0#DigitalProductPassport"
                    },
                    {
                        "type": "Operation",
                        "value": "https://w3c.github.io/vc-jws-2020/contexts/v1/"
                    }
                ]
            },
            "description": [
                {
                    "language": "en",
                    "text": "Verifiable Digital Product Passport Submodel"
                }
            ],
            "displayName": []
        }
    ]
}
```

In the submodel we included the following schema for the semantic Ids:

- -> Entity explaining that is a verifiable credential v2
    - -> Data Element with the Verifiable cREDENTIAL tYPE
        - -> Submodel -> The content from the credential
    - -> Operation -> Proof Type of the verifiable credential (operation needed to verify it)

**Comment by matbmoser** [comment]
Ok the backend is finally able to verify the credentials:


![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/13ee2701-189e-46a9-a2d9-d71fb3fc9cbc)

**Comment by matbmoser** [comment]
I have configured a dpp consumer wallet and a dpp provider wallet so the provider can sign the credentials and the consumer another instance can verify the credential for the backend!

**Comment by matbmoser** [comment]
In case the Verifiable Credential is not able to be verified this is what we get: 

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/f225a041-a482-470f-8660-0ae6a47756a5)

**Comment by matbmoser** [comment]
Status here:

- Backend implementation is 50%
- Simple wallet development is finished and its working
- Digital Twins are created and registered
- E2E flow was made using the backend
- Frontend is ready but not integrated
- Test data is done

**Comment by matbmoser** [comment]
I could auto verify and retrieve the data from the backend!

**Comment by matbmoser** [comment]
I present the first verifiable credential which is working, verified E2E and presented in the frontend !

![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/28a0c1f2-b115-474c-8c79-f3b1e5b44620)

**Comment by matbmoser** [comment]
All the PRs are create and waiting to be reviewed and merged!

**Comment by matbmoser** [comment]
Final PoC is implemented and working:


![Image](https://github.com/eclipse-tractusx/sig-release/assets/71728767/52e664c5-10f1-4904-a62a-66466dc3f588)

**Comment by saudkhan116** [comment]
Included in a DPP release `v4.0.0`

**Comment by matbmoser** [comment]
Pending to merge the following PRs:

- https://github.com/eclipse-tractusx/digital-product-pass/pull/343
- https://github.com/eclipse-tractusx/digital-product-pass/pull/341
- https://github.com/eclipse-tractusx/digital-product-pass/pull/342

**Comment by matbmoser** [comment]
Ok, Issue Documentation updated  to match developments and artifacts produced. I also added the issue ticket for the documentation which is still open. I am updating the documentation to match the implementation.

**Comment by matbmoser** [comment]
@stephanbcbauer updated the description of this feature and detailed all the aspects like dependecies etc...

**Comment by matbmoser** [comment]
Latest Version Will be published in this PR: digital-product-pass#388
