### ISSUE TITLE
Enhance and upgrade Umbrella Helm Chart (to R24.05)

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-release#710]
## Description

Continue the integration works to enable a sandbox environment - [umbrella helm chart](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-2.0.4/charts/umbrella/README.md) - so that it is possible to have an easy entrance point for developers and adopters to experience our developments hands on but also to enable e2e testing.

- [x] Upgrade to [R24.05](https://github.com/eclipse-tractusx/tractus-x-release/releases/tag/24.05)
:warning: The 24.05 Release does not include a Managed Identity Wallet (MIW) - aka the FOSS Wallet of Eclipse Tractus-X - as it was not - yet - able to cover functionalities required for the Self-Sovereign Identity Flow introduced with R24.05. To test and ship R24.05, a commercial solution was used: the Decentralized Identity Management (DIM) Wallet. To cover the wallet functionalities in the [E2E Adopter Journey Data exchange](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-2.0.4/charts/umbrella/README.md#data-exchange) and [E2E Adopter Journey Portal](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-2.0.4/charts/umbrella/README.md#get-to-know-the-portal), the [SSI DIM Wallet Stub](https://github.com/eclipse-tractusx/ssi-dim-wallet-stub) was added to the umbrella helm chart.
As an intermediate solution - before the SSI DIM Wallet Stub - the [iatp-mock](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/umbrella-2.0.4/iatp-mock).
  - [x] upgrade [currently integrated products](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/umbrella-0.16.0/charts/umbrella#install)
  - [x] integrate new (shared) products, [SSI Credential Issuer](https://github.com/eclipse-tractusx/ssi-credential-issuer) and [BDRS](https://github.com/eclipse-tractusx/bpn-did-resolution-service)
  - [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/122

- [x] Integrate missing products ([currently integrated products](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/umbrella-0.16.0/charts/umbrella#install))

  - [x] especially the shared service BPDM

- [x] Improve documentation
  - [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/155

## Impact

Enable easy entrance point for developers and adopters to experience our developments hands on but also to enable e2e testing.

## Additional information

Relates to https://github.com/eclipse-tractusx/sig-release/issues/418

Summary of the current state of integration works: https://github.com/eclipse-tractusx/sig-release/issues/418#issuecomment-2173384338

**Comment by matbmoser** [comment]
I am willing to contribute! 🔥

**Comment by matbmoser** [comment]
This is going to be worked in the R24.12 no?

**Comment by evegufy** [comment]
Updated issue with latest status and created this follow up issue: https://github.com/eclipse-tractusx/sig-release/issues/994
--> close
