### ISSUE TITLE
[R24.08] [Digital Product Pass] Release Checks

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-release#748]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: [v4.0.1](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.1)

**Leading product repository:** https://github.com/eclipse-tractusx/digital-product-pass

# General Checks

- [x] eclipse-tractusx/digital-product-pass#365

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] trg-8-01 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01
- [x] trg-8-02 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02
- [x] trg-8-03 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03
- [x] trg-8-04 https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04

# Test Results

- [x] eclipse-tractusx/digital-product-pass#366
- [x] eclipse-tractusx/digital-product-pass#368

# Features

- [X] https://github.com/eclipse-tractusx/sig-release/issues/655
- [X] https://github.com/eclipse-tractusx/sig-release/issues/651
- [X] https://github.com/eclipse-tractusx/sig-release/issues/654

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by matbmoser** [comment]
@saudkhan116 will be taking care of the review and approval from the TRG process for the Tractus-X Release R24.08. 
Tickets are tracked in the issue description and will be updated accordantly to the status.

**Comment by evegufy** [comment]
Please note that there was the following update to the issue template (see https://github.com/eclipse-tractusx/sig-release/pull/750#issuecomment-2219591340 for additional information), please take that into account for R24.08

> Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

**Comment by matbmoser** [comment]
We have released our version: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.0

Its E2E tested and also compliant with the latest QG

**Comment by saudkhan116** [comment]
As we don't need Interoperability, Data Sovereignty and Threat Modeling checks, I removed them from the description.

**Comment by ther3sa** [comment]
QG Review 24-July
- Version listed ✓
- TRG Check needs to be done
- User Journey needs to be approved
- E2E test is pending

**Comment by matbmoser** [comment]
We will need to update the version to v4.0.1. We had a bug with the EDC 0.7.3 and our charts configuration: https://github.com/eclipse-tractusx/digital-product-pass/issues/390 

-> TRG checks is done already, just need to be confirmed.

-> Maybe @stanfaldin could approve the user journey

-> E2E Tests to be completed today if the release v4.0.1 can be released today
   -> There is an issue with the dash license software (since today): https://chat.eclipse.org/#/room/!qZkRenDKdhqXlBVIfo:matrix.eclipse.org/$kaeZjRhB6YVDtbYVfmnV870a22EDhcKVlFOzXhMFFXc?via=matrix.eclipse.org&via=matrix.org
   -> I have asked in the Committer matrix chat and other products like the EDC are also waiting for it to be solved.

**Comment by matbmoser** [comment]
For compatibility documentation I have created a Compativility Matrix: https://github.com/eclipse-tractusx/digital-product-pass/blob/hotfix/policy-config/COMPATIBILITY_MATRIX.md

**Comment by stanfaldin** [comment]
> We will need to update the version to v4.0.1. We had a bug with the EDC 0.7.3 and our charts configuration: [eclipse-tractusx/digital-product-pass#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)
> 
> -> TRG checks is done already. Pending to close the ticket when the v4.0.1 is released
> 
> -> Maybe @stanfaldin could **approve the user journey**
> 
> -> E2E Tests to be completed today if the release v4.0.1 can be released today -> There is an issue with the dash license software (since today): https://chat.eclipse.org/#/room/!qZkRenDKdhqXlBVIfo:matrix.eclipse.org/$kaeZjRhB6YVDtbYVfmnV870a22EDhcKVlFOzXhMFFXc?via=matrix.eclipse.org&via=matrix.org -> I have asked in the Committer matrix chat and other products like the EDC are also waiting for it to be solved.

@catroest Do you know anything about a user journey?

**Comment by matbmoser** [comment]
@stanfaldin the user journey is simply an approval from the bussines domain owner, approving that the product is still compliant to the "product idea". There is no specific "user journey" documentation to approve. Usually was always an email approving the user journey. 

The User Journey of the DPP is "An app that is capable or retrieving and visualizing digital product passports, battery passports, transmission passports by simply introducing an ID or scanning a QR code"

And it this release I would add another statement saying, "and also be able to verify passports, according to the dpp-verification addon"

**Comment by matbmoser** [comment]
There is a bussines statement that can help with the "bussiness idea": https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/interoperability/InteroperabilityGuide.md

**Comment by matbmoser** [comment]
> We will need to update the version to v4.0.1. We had a bug with the EDC 0.7.3 and our charts configuration: [eclipse-tractusx/digital-product-pass#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)
> 
> -> TRG checks is done already. Pending to close the ticket when the v4.0.1 is released
> 
> -> Maybe [@stanfaldin](https://github.com/stanfaldin) could approve the user journey
> 
> -> E2E Tests to be completed today if the release v4.0.1 can be released today -> There is an issue with the dash license software (since today): https://chat.eclipse.org/#/room/!qZkRenDKdhqXlBVIfo:matrix.eclipse.org/$kaeZjRhB6YVDtbYVfmnV870a22EDhcKVlFOzXhMFFXc?via=matrix.eclipse.org&via=matrix.org -> I have asked in the Committer matrix chat and other products like the EDC are also waiting for it to be solved.

By the way @ther3sa I could find the reason why we can't run the IP checks dash license tool: https://status.maven.org/#
There is a service from maven that is currently down, since yesterday they are having problems there....

**Comment by matbmoser** [comment]
Ok I could finally resolve the issue. Tommorow we will create the release

**Comment by matbmoser** [comment]
New release tag published: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.1

**Comment by matbmoser** [comment]
All security checks have passed!

**Comment by saudkhan116** [comment]
> > New release tag published: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.1
> 
> perfect :) Could you update the version link in your description to 4.0.1 too? :)

Its updated there

**Comment by saudkhan116** [comment]
The E2E tests are executed, and passed!

**Comment by matbmoser** [comment]
@ds-hzimmer could you provide the Test management approval?

**Comment by ds-meberle** [comment]
@matbmoser 
E2E Tests have been performed successfully. Thank You!

**Comment by stanfaldin** [comment]
> > We will need to update the version to v4.0.1. We had a bug with the EDC 0.7.3 and our charts configuration: [eclipse-tractusx/digital-product-pass#390](https://github.com/eclipse-tractusx/digital-product-pass/issues/390)
> > -> TRG checks is done already. Pending to close the ticket when the v4.0.1 is released
> > -> Maybe [@stanfaldin](https://github.com/stanfaldin) could approve the user journey
> > -> E2E Tests to be completed today if the release v4.0.1 can be released today -> There is an issue with the dash license software (since today): https://chat.eclipse.org/#/room/!qZkRenDKdhqXlBVIfo:matrix.eclipse.org/$kaeZjRhB6YVDtbYVfmnV870a22EDhcKVlFOzXhMFFXc?via=matrix.eclipse.org&via=matrix.org -> I have asked in the Committer matrix chat and other products like the EDC are also waiting for it to be solved.
> 
> By the way @ther3sa I could find the reason why we can't run the IP checks dash license tool: https://status.maven.org/# There is a service from maven that is currently down, since yesterday they are having problems there.... Hope that we can release today. The PR is ready: [eclipse-tractusx/digital-product-pass#388](https://github.com/eclipse-tractusx/digital-product-pass/pull/388)

@ther3sa & @matbmoser & @saudkhan116 : According to my understanding and consultation with experts from the CX DPP Expert Group, I hereby confirm the consistency of the release version v4.0.1. with the DPP User Story.

**Comment by matbmoser** [comment]
Cool! Thank you @stanfaldin!!

@ther3sa this means that we officially passed QG?

**Comment by ther3sa** [comment]
Congrats:
 Quality Gate fully approved with all necessary pre-requisites fulfilled! 
 Thanks for all your efforts! :)

**Comment by saudkhan116** [comment]
> Congrats:  Quality Gate fully approved with all necessary pre-requisites fulfilled!   Thanks for all your efforts! :)

Thank you very much!

**Comment by matbmoser** [comment]
Super @ther3sa! Thank you very much :)
