### ISSUE TITLE
Roadmap#148 Enable Portal for Multi-Identity Clearing House for Regional Identity Verification

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/sig-release#904]
## Overview

The implementation of multiple identity clearing houses is crucial for enabling regional identity verification in the Catena-X ecosystem, particularly for non-EU participants. This system will allow trusted third parties in different regions to perform identity verification while maintaining compliance with established standards. This initiative is particularly relevant as organizations like CAICT and Huawei seek to establish their own clearing house for onboarding in China.

## Explain the topic in 2 sentences

The need for multiple identity clearing houses stems from the requirement to handle identity verification across different geographical regions while ensuring trust and sovereignty in data exchange.

## What's the benefit?

1. Trust Enhancement
  - Enables secure identity verification across different regions through trusted third parties
  - Can establish audit logging during the onboarding process
  - Can establish transparency 
2. Operational Efficiency
  - Can quickly respond to changing circumstances (merger and acquisition, data breaches, fraudulent behavior) through re-validtions
  - Supports multiple channels for identity verification to accommodate various regional requirements

### Operational Dependencies
- Integration with existing [Tractus-X components](https://github.com/eclipse-tractusx/tractus-x-release/releases)
- Compliance with Gaia-X Trust Framework requirements: [Targus Release](https://github.com/eclipse-tractusx/tractus-x-release/releases)
- Connection to external Clearing House services (T-Systems)

### Concept
- Catena-X Portal Team need to define the concept:  
https://github.com/catenax-eV/sig-roadmap/issues/148

### Open Question / Risks
- No C-X Expert group for Portal
- Currently the signed credential for self-description are stored in the Portal database and not the identity wallet and the issuer of the participant onboarding isn't visible in the portal. We need a discussion in the Catena-X Onboard/Offboarding working group.
- if more than one Clearing House cover one region, which behavior should be implemented
- SD Factory for Tagus Release

## Detailed explanation

+ https://github.com/catenax-eV/sig-roadmap/issues/148 (NSC committee / Portal Team)
+ https://github.com/catenax-eV/sig-roadmap/issues/221 (Lead by C-X Internationalization Commiteee)

## Current implementation

The current implementation supports one clearing house and follow the standard: [CX-0006 Registration and Initial Onboarding v2.0.1](https://catenax-ev.github.io/docs/standards/CX-0006-RegistrationAndInitialOnboarding)

## Proposed improvements

- configured list of Clearing houses per covered region in portal component 
- send the validation request to the configured Clearing house for validation and notarization step
- visualize the responsible clearing house per participant in the portal (issuer in the participant credential)

### Contributor

Contributor 1: @tfjanjua, 
Contributor 2: @dhiren-singh-007 

### Committer 

- @oyo
- @ntruchsess
- @Phil91
- @evegufy
- @matbmoser 

## User Stories

- Issue 1, linked to specific repository
- Issue 2, linked to another specific repository

## Acceptance Criteria

- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3

#### Steps

1. Do something
2. Click something
3. Add something

#### Expected Result

1. Expectation
2. Expectation
3. Expectation

## Architectural Relevance

The following items are ensured (answer: yes) after this issue is implemented:

- [ ] This feature aligns with our current architectural guidelines
  - **Data Sovereignty:** All data sharing activities across company boundaries follow the [Catena-X Regulatory Framework](https://catenax-ev.github.io/docs/next/regulatory-framework/governance-framework), in particular the [Data Exchange Governance](https://catenax-ev.github.io/docs/next/regulatory-framework/20000ft/data-exchange-governance), and the [Dataspace Protocol](https://docs.internationaldataspaces.org/dataspace-protocol/overview/readme) via a compliant Connector (like the [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc) or similar, see [Connector KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/connector-kit))
    - [ ] [CX-0010 Business Partner Number](https://catenax-ev.github.io/docs/next/standards/CX-0010-BusinessPartnerNumber)
    - [ ] [CX-0013 Identity of Member Companies](https://catenax-ev.github.io/docs/next/standards/CX-0013-IdentityOfMemberCompanies)
    - [ ] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
    - [ ] [CX-0049 DID Document Schema](https://catenax-ev.github.io/docs/next/standards/CX-0049-DIDDocumentSchema)
    - [ ] [CX-0050 Framework Agreement Credential](https://catenax-ev.github.io/docs/next/standards/CX-0050-FrameworkAgreementCredential)
    - [ ] [CX-0149 Verified Company Identity](https://catenax-ev.github.io/docs/next/standards/CX-0149-Dataspaceidentityandidentification)
  - **Interoperability:** Digital Twins are used (compliant to the [Digital Twin KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/digital-twin-kit) and the [Industry Core KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/industry-core-kit))
    - [ ] [CX-0001 EDC Discovery API](https://catenax-ev.github.io/docs/next/standards/CX-0001-EDCDiscoveryAPI)
    - [ ] [CX-0002 Digital Twins in Catena-X](https://catenax-ev.github.io/docs/next/standards/CX-0002-DigitalTwinsInCatenaX)
    - [ ] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
  - **Data Format:**
    - [ ] The data model is based on a [published Semantic Model](https://github.com/eclipse-tractusx/sldt-semantic-models)
- [ ] The impact on the overall system architecture has been assessed. The Feature does not require changes to the architecture or any existing standard? Please have a look here on the [overarching architecture](https://eclipse-tractusx.github.io/docs/tutorials/e2e/inform/architecture)
- [ ] Potential risks or conflicts with existing architecture has been assessed

**Justification:** _(Fill this out, if at least one of the checkboxes above cannot be ticked. Contact the Architecture Management Committee to get an approval for the justification)_

## Additional information

- [ ] I am aware that my request may not be developed if no developer can be found for it. I'll try to contribute a developer (bring your own developer)

**Comment by MaximilianHauer** [comment]
@ma3u  wer von cofinity ist hier im lead für das Thema ? derjenige sollte das Thema auch für das sig-release einsteuern. Ich habe hier damals nur einen "puffer" angelegt damit das Thema nicht durch rutscht.

**Comment by ma3u** [comment]
Erik Wiegert

**Comment by stephanbcbauer** [comment]
Some hints from Release Management (@ther3sa) and Tractus-X Project Lead (@stephanbcbauer)
- Status currently in Inbox. ⇾ Only features with status backlog are considered in open planning
- Please add missing sections from the feature template, or fill them out
- Please add contributor and committer
- Please add assignee (overall responsible person who drives the feature)

**Comment by evegufy** [comment]
Committers:
@oyo
@ntruchsess 
@Phil91 
@evegufy

**Comment by evegufy** [comment]
@ybidois as discussed yesterday, the description should be updated by you. If you don't want to create new issue, I have the permission to update the existing description (and title), if you provide that information as comment, I can paste it accordingly

**Comment by stephanbcbauer** [comment]
@ybidois mentioned ⇾ still in discussion

**Comment by ma3u** [comment]
In Catena-X Board we already create a Roadmap item with further informations:
+ https://github.com/catenax-eV/sig-roadmap/issues/148

**Comment by matbmoser** [comment]
I am interested to keep informed on this part

**Comment by ma3u** [comment]
Contributors: @dhiren-singh-007, @tfjanjua

**Comment by ma3u** [comment]
CAICT will check against this company verification methods:

## Combination of the 3 verification methods guarantee a very good coverage in China:
 
### Unified Social Credit Code (USCC):
The USCC is a standardized 18-digit code used in China for identifying and verifying enterprises and organizations. It provides a unified standard for identification and enhances transparency. However, it is specific to mainland China and not used in regions like Hong Kong, Macau. This limits its global applicability for Catena-X. Maintained by Government contain the automotive enterprise. 

###  Industrial Internet Identifier:
There is limited information in the search results about a specific "Industrial Internet Identifier". However, result mentions "identity resolution technology" in the context of the Industrial Internet of Things (IIoT). This could potentially be relevant for Catena-X, but there's not enough detail to assess its coverage.

###  BID ([did:bid](https://github.com/teleinfo-bif/bid/tree/master/doc/en)): [DID Methods - Various](https://decentralized-id.com/web-standards/w3c/decentralized-identifier/did-methods/) 
BID provides distributed identifiers and blockchain-based digital identity services for people, enterprises, devices and digital objects. It aims to build a decentralized, data-secure, privacy-protected and flexible identifier system that addresses trusted connections among people, enterprises, devices and digital objects，enabling the vision of the Internet of Things and trust ingress with everything.

**Comment by ma3u** [comment]
@MaximilianHauer : Can you add this text to the issue:

## Overview

The implementation of multiple identity clearing houses is crucial for enabling regional identity verification in the Catena-X ecosystem, particularly for non-EU participants. This system will allow trusted third parties in different regions to perform identity verification while maintaining compliance with established standards. This initiative is particularly relevant as organizations like CAICT and Huawei seek to establish their own clearing house for onboarding in China.

## Explain the topic in 2 sentences

The need for multiple identity clearing houses stems from the requirement to handle identity verification across different geographical regions while ensuring trust and sovereignty in data exchange.

## What's the benefit?

1. Trust Enhancement
  - Enables secure identity verification across different regions through trusted third parties
  - Can establish audit logging during the onboarding process
  - Can establish transparency 
2. Operational Efficiency
  - Can quickly respond to changing circumstances (merger and acquisition, data breaches, fraudulent behavior) through re-validtions
  - Supports multiple channels for identity verification to accommodate various regional requirements

## What are the Risks/Dependencies ?

### Operational Dependencies
- Integration with existing [Tractus-X components](https://github.com/eclipse-tractusx/tractus-x-release/releases)
- Compliance with Gaia-X Trust Framework requirements: [Targus Release](https://github.com/eclipse-tractusx/tractus-x-release/releases)
- Connection to external Clearing House services (T-Systems)

### Concept
- Catena-X Portal Team need to define the concept:  
https://github.com/catenax-eV/sig-roadmap/issues/148

### Open Question / Risks
- No C-X Expert group for Portal
- Currently the signed credential for self-description are stored in the Portal database and not the identity wallet and the issuer of the participant onboarding isn't visible in the portal. We need a discussion in the Catena-X Onboard/Offboarding working group.
- if more than one Clearing House cover one region, which behavior should be implemented
- SD Factory for Tagus Release

## Detailed explanation

+ https://github.com/catenax-eV/sig-roadmap/issues/148 (NSC committee / Portal Team)
+ https://github.com/catenax-eV/sig-roadmap/issues/221 (Lead by C-X Internationalization Commiteee)

## Current implementation

The current implementation supports one clearing house and follow the standard: [CX-0006 Registration and Initial Onboarding v2.0.1](https://catenax-ev.github.io/docs/standards/CX-0006-RegistrationAndInitialOnboarding)

## Proposed improvements

- configured list of Clearing houses per covered region in portal component 
- send the validation request to the configured Clearing house for validation and notarization step
- visualize the responsible clearing house per participant in the portal (issuer in the participant credential)

## Feature Team

### Contributor

Contributor 1: @tfjanjua, 
Contributor 2: @dhiren-singh-007 

### Committer 

Contributor 3: @Phil91

**Comment by ma3u** [comment]
Please adjust the standard:  [CX-0006 Registration and Initial Onboarding v2.0.1](https://catenax-ev.github.io/docs/standards/CX-0006-RegistrationAndInitialOnboarding)

For R25.06 Deadline by Feb 21th for standard request:
https://github.com/catenax-eV/product-standardization-prod/issues

Add CX-Nr. CX-0006  and Standard Registration and Initial Onboarding v2.0.1

Need to change to v2.1.1, because  MUST critera if the new participant is located in China.

**Comment by ma3u** [comment]
Please adjust the standard:  [CX-0006 Registration and Initial Onboarding v2.0.1](https://catenax-ev.github.io/docs/standards/CX-0006-RegistrationAndInitialOnboarding)

For R25.06 Deadline by Feb 21th for standard request:
https://github.com/catenax-eV/product-standardization-prod/issues

Add CX-Nr. CX-0006  and Standard Registration and Initial Onboarding v2.0.1

Need to change to v2.1.1, because  MUST critera if the new participant is located in China.

**Comment by dorkabcox** [comment]
In progress, but coming in the next release (25.06), we'll provide further detail soon.

**Comment by dorkabcox** [comment]
Dear Community, please note that Cofinity-X will not be contributing with the Multi-ClearingHouse concept yet - will continue the work in 25.06. The topic matured significantly in the last months and we performed a lot of analysis. Decision must be made regarding designing the logic now, then we need to build the solution.

**Comment by stephanbcbauer** [comment]
was presented in open planning 25.06.

**Comment by evegufy** [comment]
Hi @dorkabcox @tfjanjua @typecastcloud I might have noticed a hole in the requirements analysis: I assume also the sd-factory needs to enabled to support multiple clearinghouses, could you please check that and provide information about how this is managed? The relevant processes are the gaia-x compliance during onboarding and the connector registration.

cc: @MaximilianHauer @Phil91 @ds-hzimmer

**Comment by tfjanjua** [comment]
> Hi [@dorkabcox](https://github.com/dorkabcox) [@tfjanjua](https://github.com/tfjanjua) [@typecastcloud](https://github.com/typecastcloud) I might have noticed a hole in the requirements analysis: I assume also the sd-factory needs to enabled to support multiple clearinghouses, could you please check that and provide information about how this is managed? The relevant processes are the gaia-x compliance during onboarding and the connector registration.
> 
> cc: [@MaximilianHauer](https://github.com/MaximilianHauer) [@Phil91](https://github.com/Phil91) [@ds-hzimmer](https://github.com/ds-hzimmer)

Thank you for highlighting it @evegufy , I already had discussed this SD Factory topic with @Phil91 and I have some capacity to look into this topic along with this multi-clearinghouse topic.

I had suggested to either introduce the concept of Multi-SdFactory or simply add a parameter like `ClearinghouseConnectDisabled` to each clearinghouse so that the SD-Factory step of each clearinghouse can be set to True or False.

But I'll discuss it with Phil a bit more and proceed accordingly.

**Comment by evegufy** [comment]
> Thank you for highlighting it [@evegufy](https://github.com/evegufy) , I already had discussed this SD Factory topic with [@Phil91](https://github.com/Phil91) and I have some capacity to look into this topic along with this multi-clearinghouse topic.
> 
> I had suggested to either introduce the concept of Multi-SdFactory or simply add a parameter like `ClearinghouseConnectDisabled` to each clearinghouse so that the SD-Factory step of each clearinghouse can be set to True or False.
> 
> But I'll discuss it with Phil a bit more and proceed accordingly.

@tfjanjua what you mention regarding an introducing `ClearinghouseConnectDisabled to each clearinghouse so that the SD-Factory step of each clearinghouse can be set to True or False` is not an option because because permanently disabling the connection to the SD-factory is not CX standard compliant, see https://catenax-ev.github.io/release-notes#further-scope-clarification.
Also, I don't understand what you mean with `Multi-SdFactory` or more how that would solve this issue: then we just would have multiple sd-factory instances which would not be able to handle this regional/multiple clearinghouse feature.

The point of my comment was that somebody should coordinate with responsibles from [sd-factory](https://github.com/eclipse-tractusx/sd-factory) and check if they can enable the sd-factory component for this feature otherwise this feature won't be usable.

**Comment by tfjanjua** [comment]
> > Thank you for highlighting it [@evegufy](https://github.com/evegufy) , I already had discussed this SD Factory topic with [@Phil91](https://github.com/Phil91) and I have some capacity to look into this topic along with this multi-clearinghouse topic.
> > I had suggested to either introduce the concept of Multi-SdFactory or simply add a parameter like `ClearinghouseConnectDisabled` to each clearinghouse so that the SD-Factory step of each clearinghouse can be set to True or False.
> > But I'll discuss it with Phil a bit more and proceed accordingly.
> 
> [@tfjanjua](https://github.com/tfjanjua) what you mention regarding an introducing `ClearinghouseConnectDisabled to each clearinghouse so that the SD-Factory step of each clearinghouse can be set to True or False` is not an option because because permanently disabling the connection to the SD-factory is not CX standard compliant, see https://catenax-ev.github.io/release-notes#further-scope-clarification. Also, I don't understand what you mean with `Multi-SdFactory` or more how that would solve this issue: then we just would have multiple sd-factory instances which would not be able to handle this regional/multiple clearinghouse feature.
> 
> The point of my comment was that somebody should coordinate with responsibles from [sd-factory](https://github.com/eclipse-tractusx/sd-factory) and check if they can enable the sd-factory component for this feature otherwise this feature won't be usable.

@evegufy firstly I think introducing `ClearinghouseConnectDisabled to each clearinghouse so that the SD-Factory step of each clearinghouse can be set to True or False` will give a possibility to decide on a country-specific basis that which country-specific SD Factory step should be skipped instead of permanently disabling the connection to the SD-factory.

secondly, I meant of `Multi-SdFactory` that we could specify country-specific configuration of SD-Factory as we just did for Multi-Clearinghouse but we can discuss and decide any one approach. I personally think the first option, to have `ClearinghouseConnectDisabled` bit with each (country-specific) clearinghouse would be a good option because its not necessary that all clearinghouse service providers would be providing the SD-Factory (compliance) option separately so, introducing the `ClearinghouseConnectDisabled` bit would give us option to skip the SD-Factory where it is not available.

Your last point is really valid, what if a clearinghouse service provider would also provide SD-Factory service separately... so, in this case we can make `ClearinghouseConnectDisabled` as False and in this case process will call the sd-factory but then how this country-specific sd-factory request would be handled in sd-factory... so, yes we would need to discuss this topic with sd-factory peeps as well.

**Comment by MaximilianHauer** [comment]
hi all,

this issue resulted out of the need to be able to handle china. 
therefor my expectation would be that we have a clear understanding what the dependency from china would be and how this would affect our current implementation logic. 

i assume we have a 2 step approach here.
1.) what is the need to enable china and what does this mean for our architecture and our standards 
2.) what is the overall architecture we want to aim for e.g. multi sd-factory, sd-factory only in europe , .... and what this means for out standards 

the story from phil was basically a starting point we offered to provide an overview how we could do this, nevertheless i would expect that there is a gap analysis. 

as cofinity is in the lead of the china onboarding,from what i understood, we should have a shot alignment meeting wiht catena-x und cofinity-x ? 

@stephanbcbauer , @thomasobermeyer

**Comment by stephanbcbauer** [comment]
@tfjanjua , @ThomasObermeyer, since we talked about these concepts as preperation for handling Clearinghouse in China and maybe as preparation for the [upload of the certificates](https://github.com/catenax-eV/sig-roadmap/issues/452) during onboarding progress, my question would be, where are the results of these concepts? Do we have diagrams? Decision records? documentation?

**Comment by stephanbcbauer** [comment]
> as discussed in today's portal (self-arranged) refinement, the proposed technical solution by [@tfjanjua](https://github.com/tfjanjua) [eclipse-tractusx/portal-backend#1343](https://github.com/eclipse-tractusx/portal-backend/issues/1343) is not Catena-X standard compliant because it would not enable the creation of self description documents (SD) for region specific clearinghouses. The current [Catena-X clarification](https://catenax-ev.github.io/release-notes#further-scope-clarification) for the the SD Factory states that "the creation of the SD can now occur at a later stage." but the proposed technical solution solution wouldn't allow the creation the SD at all, also not at a later stage, therefor **the current implementation for multi region clearinghouse and also the the proposed technical solution are not Catena-X standard compliant**. [@dorkabcox](https://github.com/dorkabcox) will discuss with [@ThomasObermeyer](https://github.com/ThomasObermeyer) [@stephanbcbauer](https://github.com/stephanbcbauer) if the [Catena-X clarification](https://catenax-ev.github.io/release-notes#further-scope-clarification) can be adjusted to allow the proposed technical solution.
> 
> [@ds-hzimmer](https://github.com/ds-hzimmer) [@MonikaJacobsen](https://github.com/MonikaJacobsen) please be aware of this because it could impact the testing phase for 25.06.

@jSchuetz88 FYI

**Comment by HFocken** [comment]
@evegufy & @dorkabcox as requested in your mail here a quick confirmation: region-specific clearing houses outside of Europe (!) do not necessarily need to be Gaia-X Digital Clearing Houses and/or Gaia-X compliant. Reason being that the Gaia-X brand does not necessarily help us in regions such as China / Japan or similar. To date, China is the most urgent stakeholder in this regard.

@jSchuetz88 @ther3sa we need to ensure that we bring the Operating Model (potentially standards) up to code on this one, once we made progress.
