### ISSUE TITLE
[PURIS KIT] PURIS KIT maintenance

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-release#911]
# Overview

## Explain the topic in 2 sentences
We want to improve the PURIS KIT with business-wise content and further implementation support.

## What's the benefit?

Pull more adopters by explaining the ideas and the implementation pragmatically.

## What are the Risks/Dependencies ?

No

### Current implementation
See [Kit](https://eclipse-tractusx.github.io/docs-kits/next/kits/PURIS%20Kit/Adoption%20View%20PURIS%20Kit), [files](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/main/docs-kits/kits/PURIS%20Kit)

### Contributor

- @Clemens-L-Schwarz 
- Contributor 2

### Committer

- @tom-rm-meyer-ISST 
- Committer 2

## User Stories

- [x] eclipse-tractusx/eclipse-tractusx.github.io#1081
- [x] eclipse-tractusx/eclipse-tractusx.github.io#1082
- [x] eclipse-tractusx/eclipse-tractusx.github.io#1083

## Acceptance Criteria

- [x] Quality Gate Ticket has been created (https://github.com/eclipse-tractusx/sig-release/issues/1494)
- [ ] Quality Gate has been passed

## Test Cases

Not applicable 

## Architectural Relevance

The following items are ensured (answer: yes) after this issue is implemented:

- [x] This feature aligns with our current architectural guidelines
  - **Data Sovereignty:** All data sharing activities across company boundaries follow the [Catena-X Regulatory Framework](https://catenax-ev.github.io/docs/next/regulatory-framework/governance-framework), in particular the [Data Exchange Governance](https://catenax-ev.github.io/docs/next/regulatory-framework/20000ft/data-exchange-governance), and the [Dataspace Protocol](https://docs.internationaldataspaces.org/dataspace-protocol/overview/readme) via a compliant Connector (like the [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc) or similar, see [Connector KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/connector-kit))
    - [x] [CX-0010 Business Partner Number](https://catenax-ev.github.io/docs/next/standards/CX-0010-BusinessPartnerNumber)
    - [x] [CX-0013 Identity of Member Companies](https://catenax-ev.github.io/docs/next/standards/CX-0013-IdentityOfMemberCompanies)
    - [x] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
    - [x] [CX-0049 DID Document Schema](https://catenax-ev.github.io/docs/next/standards/CX-0049-DIDDocumentSchema)
    - [x] [CX-0050 Framework Agreement Credential](https://catenax-ev.github.io/docs/next/standards/CX-0050-FrameworkAgreementCredential)
    - [x] [CX-0149 Verified Company Identity](https://catenax-ev.github.io/docs/next/standards/CX-0149-Dataspaceidentityandidentification)
  - **Interoperability:** Digital Twins are used (compliant to the [Digital Twin KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/digital-twin-kit) and the [Industry Core KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/industry-core-kit))
    - [x] [CX-0001 EDC Discovery API](https://catenax-ev.github.io/docs/next/standards/CX-0001-EDCDiscoveryAPI)
    - [x] [CX-0002 Digital Twins in Catena-X](https://catenax-ev.github.io/docs/next/standards/CX-0002-DigitalTwinsInCatenaX)
    - [x] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
  - **Data Format:**
    - [x] The data model is based on a [published Semantic Model](https://github.com/eclipse-tractusx/sldt-semantic-models)
- [x] The impact on the overall system architecture has been assessed. The Feature does not require changes to the architecture or any existing standard? Please have a look here on the [overarching architecture](https://eclipse-tractusx.github.io/docs/tutorials/e2e/inform/architecture)
- [x] Potential risks or conflicts with existing architecture has been assessed

**Justification:** _(Fill this out, if at least one of the checkboxes above cannot be ticked. Contact the Architecture Management Committee to get an approval for the justification)_

## Additional information

- [x] I am aware that my request may not be developed if no developer can be found for it. I'll try to contribute a developer (bring your own developer)

**Comment by stephanbcbauer** [comment]
Some hints from Release Management (@ther3sa) and Tractus-X Project Lead (@stephanbcbauer)
- Status currently in Inbox. ⇾ Only features with status backlog are considered in open planning

**Comment by tom-rm-meyer-ISST** [comment]
Whenever making changes to the KIT

- please assign @tom-rm-meyer-ISST as a reviewer
-  @tom-rm-meyer-ISST provides support for KIT methods

**Comment by tom-rm-meyer-ISST** [comment]
Moved to 25.06 due to insufficient progress

**Comment by Kuehner-A** [comment]
Update should be finished until 07/25. Maybe 25.09 with all the feedbacks from EG?

**Comment by ther3sa** [comment]
Note from Release Management (@ther3sa) and Tractus-X Project Lead (@stephanbcbauer):
The 25.06 release has been successfully released.

To ensure transparency and alignment, please either:

- Close this feature if it has been implemented as part of this release, or
- Update the milestone to 25.09 if it has not yet been completed.

Thank you!

**Comment by tom-rm-meyer-ISST** [comment]
Removed eclipse-tractusx/eclipse-tractusx.github.io/issues/1128 from roadmap item. Will be handled after practical application
