### ISSUE TITLE
EDC - Allow consistent request tracking across control and data plane

### ISSUE THREAD

**Issue by gerbigf** [eclipse-tractusx/sig-release#930]
# Overview

## Explain the topic in 2 sentences

Allow consistent request tracking across control and data plane within one Connector of one company. Out of scope for this feature is consistent tracking across multiple services (Wallet, DTR, EDC) and across multiple partners. 

Currently, there's a disconnect between logs in control and data plane which makes it hard to debug and trace requests when there's a lot of traffic in the EDC. This feature looks into improving request tracking by e.g. adding TransferProcess Identifiers to data plane logs. 

## What's the benefit?
Increased usability due to better log readability.

## What are the Risks/Dependencies ?
No breaking change, just slight improvements

### Current implementation

Logs of the data plane don't show meaningful tracking information so that it's hard to correlate a transfer process with the actual data transfer. There is a data flow ID but that doesn't provide any information about the corresponding tranfer-process::

[0;34mDEBUG 2024-10-07T15:35:50.479050161 [DataPlaneManagerImpl] DataFlow 9ce1198c-a742-4670-8932-655d3f4c47e6 is now in state RECEIVED[0m 

### Proposed improvements

The implementation details will be defined during work on the story. A first proposal is, to add Transfer Process IDs to the data plane logs. Probably we can also further improve log traceability by adding e.g. information about the asset-id that's requested. 

### Contributor
- BMW: @gerbigf
- BMW: @rafaelmag110 
- BMW: @bmg13

### Committer
- @jimmarino (For Review)
- @paullatzelsperger (For Review)

## User Stories

- tbd

## Acceptance Criteria

- Same unique identifier is used in EDC Control and Data Plane
- It's possible to track a data request from start of the data transfer to the completed transfer

#### Steps

1. Create a transfer process via the data management API
2. Issue a request against the data plane

#### Expected Result

1. The Transfer Process ID is shown in the data plane logs

## Architectural Relevance

The following items are ensured (answer: yes) after this issue is implemented:

- [x] This feature aligns with our current architectural guidelines
  - **Data Sovereignty:** All data sharing activities across company boundaries follow the [Catena-X Regulatory Framework](https://catenax-ev.github.io/docs/next/regulatory-framework/governance-framework), in particular the [Data Exchange Governance](https://catenax-ev.github.io/docs/next/regulatory-framework/20000ft/data-exchange-governance), and the [Dataspace Protocol](https://docs.internationaldataspaces.org/dataspace-protocol/overview/readme) via a compliant Connector (like the [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc) or similar, see [Connector KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/connector-kit))
    - [x] [CX-0010 Business Partner Number](https://catenax-ev.github.io/docs/next/standards/CX-0010-BusinessPartnerNumber)
    - [x] [CX-0013 Identity of Member Companies](https://catenax-ev.github.io/docs/next/standards/CX-0013-IdentityOfMemberCompanies)
    - [x] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
    - [x] [CX-0049 DID Document Schema](https://catenax-ev.github.io/docs/next/standards/CX-0049-DIDDocumentSchema)
    - [x] [CX-0050 Framework Agreement Credential](https://catenax-ev.github.io/docs/next/standards/CX-0050-FrameworkAgreementCredential)
    - [x] [CX-0149 Verified Company Identity](https://catenax-ev.github.io/docs/next/standards/CX-0149-Dataspaceidentityandidentification)
  - **Interoperability:** Digital Twins are used (compliant to the [Digital Twin KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/digital-twin-kit) and the [Industry Core KIT](https://eclipse-tractusx.github.io/docs-kits/next/category/industry-core-kit))
    - [x] [CX-0001 EDC Discovery API](https://catenax-ev.github.io/docs/next/standards/CX-0001-EDCDiscoveryAPI)
    - [x] [CX-0002 Digital Twins in Catena-X](https://catenax-ev.github.io/docs/next/standards/CX-0002-DigitalTwinsInCatenaX)
    - [x] [CX-0018 Data Space Connectivity (EDC)](https://catenax-ev.github.io/docs/next/standards/CX-0018-DataspaceConnectivity)
  - **Data Format:**
    - [x] The data model is based on a [published Semantic Model](https://github.com/eclipse-tractusx/sldt-semantic-models)
- [x] The impact on the overall system architecture has been assessed. The Feature does not require changes to the architecture or any existing standard? Please have a look here on the [overarching architecture](https://eclipse-tractusx.github.io/docs/tutorials/e2e/inform/architecture)
- [x] Potential risks or conflicts with existing architecture has been assessed

**Justification:** _(Fill this out, if at least one of the checkboxes above cannot be ticked. Contact the Architecture Management Committee to get an approval for the justification)_

## Additional information

- [x] I am aware that my request may not be developed if no developer can be found for it. I'll try to contribute a developer (bring your own developer)

**Comment by stephanbcbauer** [comment]
This issue is already done, but was somehow not closed. Maybe workflow is deactivated ⇾ issue is closed manually. Thanks
