### ISSUE TITLE
Upgrade docusaurus (tractus-x webpage) to newest version 3.X

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#985]
# Overview
This feature will upgrade the Tractus-X website's Docusaurus framework from version 2.2.0 to 3.X to enhance security by addressing vulnerabilities in outdated libraries. The upgrade involves removing deprecated plugins and implementing a new method to display API specifications across different KIT versions.

## Explain the topic in 2 sentences
To update Tractus-X’s webpage to Docusaurus 3.X, we’ll remove unmaintained plugins and introduce API Hub for consistent API spec presentation across KIT versions, addressing syntax requirements imposed by the new MDX checker.

## What's the benefit?
This update improves website security, reduces dependency on outdated plugins, and standardizes the API display across various KIT versions.

## What are the Risks/Dependencies?
- Removing the Open API plugin will affect older KITs that use it to generate files for Swagger UI. The transition to API Hub must ensure compatibility with both older and newer KITs.
- The new MDX checker enforces syntax requirements that may require revisions to multiple KITs’ markdown files.
- Certain dependencies or custom components may need adjustments for compatibility with Docusaurus 3.X.

## Detailed Explanation
This upgrade will:
- Replace the outdated Open API plugin with API Hub, ensuring API spec availability across all KITs.
- Remove the obsolete remote plugin, which is no longer in use.
- Address MDX syntax issues raised by the Docusaurus 3.X checker, with errors resolved in the related KITs’ MDX and MD files.

### Current Implementation
The current webpage uses Docusaurus 2.2.0 with an Open API plugin to display Swagger UI for some KITs, and a remote plugin that is no longer in use. Syntax rules for markdown files are less strict, resulting in potential errors when checked with the MDX checker in the new version.

### Proposed Improvements
1. Upgrade to Docusaurus 3.X.
2. Remove the Open API and remote plugins.
3. Integrate API Hub for consistent API presentation across KIT versions.
4. Resolve MDX checker errors in the related KITs’ MDX and MD files.

### Contributor
- @jSchuetz88 
- @manojava-gk
- @ybidois 
- @stephanbcbauer 

### Committer
- @stephanbcbauer 
- @ClosedSourcerer 
- @arnoweiss 
- @manojava-gk 

## User Stories

- [ ] Update the Tractus-X website to Docusaurus 3.6.0 to ensure security and library compatibility.
- [ ] Remove outdated plugins (Open API and remote) to maintain plugin compatibility and security.
- [ ] Transition KITs’ API specifications to be displayed via the new API Hub.
- [ ] Resolve MDX checker errors in KITs’ MDX and MD files for syntax compliance.
- [ ] Provide a reference implementation for setting up the API Hub for KITs’ API specs.
- [ ] Update documentation and guidelines on required MDX syntax for contributors.

## KITs to be adapted

(please create issue for each KIT in for [github.io](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/new/choose) with the following [template](https://github.com/eclipse-tractusx/sig-release/issues/985#issuecomment-2736030816)
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1217
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1234
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1218
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1231
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1207
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1219
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1227
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1220
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1235
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1206
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1232
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1221
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1208
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1222
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1233
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1240
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1228
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1224
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1225
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1230
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1209
- [ ] eclipse-tractusx/eclipse-tractusx.github.io#1223
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1241

## Acceptance Criteria
- [ ] Docusaurus core updated to 3.6.0 with deprecated plugins removed
- [ ] All API specs are accessible through the new API Hub
- [ ] MDX checker errors resolved in the related KITs’ MDX and MD files

#### Steps
1. Navigate to API documentation for both old and new KITs.
2. Verify API specs are displayed via API Hub.

#### Expected Result
1. API specs are consistently displayed in both old and new KIT versions.

#### Steps

1. Add a dummy kit (or maybe a demo kit) as example and for testing

#### Expected Result
1. The KIT is displayed correctly without any errors and the correct API version and spec is linked.

## Additional information

- [X] I am aware that my request may not be developed if no developer can be found for it. I'll try to contribute a developer (bring your own developer)

**Comment by stephanbcbauer** [comment]
Some hints from Release Management (@ther3sa) and Tractus-X Project Lead (@stephanbcbauer)
- **Status currently in Inbox**. ⇾ Only features with status backlog are considered in open planning
- Please add missing sections from the feature template, or fill them out
- Please add assignee (overall responsible person who drives the feature)

**Comment by stephanbcbauer** [comment]
@@jSchuetz88, @manojava-gk, @ybidois sorry for the short notice. I nearly forget to refine my feature. Can you please provide feedback on this? Thx

**Comment by jSchuetz88** [comment]
Looks good to me, lets do it +1

**Comment by ybidois** [comment]
@stephanbcbauer What about adding a second test case about "Adding a dummy kit" and see if it displays correctly along the current kits?

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer What about adding a second test case about "Adding a dummy kit" and see if it displays correctly along the current kits?

Thank you very much.I will add a second test case. What do you think about the overall description? Does it make sense? Is this feature or description? Good quality?

**Comment by stephanbcbauer** [comment]
@ybidois, @jSchuetz88  added the test case and put the status to Backlog

**Comment by manojava-gk** [comment]
this looks good to me

**Comment by stephanbcbauer** [comment]
@manojava-gk, @ybidois deleted you from the committer section, since you are not committers, correct. But i think overall that's an excellent contribution.

**Comment by ClosedSourcerer** [comment]
Please make sure that the mermaid plugin gets updated as well.
Newer version should support chart types: mindmap, block-beta and xychart-beta

**Comment by ClosedSourcerer** [comment]
@MWADCM @LukasSchmetz 
We need to change our KIT and migrate the API documentation to the API Hub (For all Released KIT Versions)

**Comment by LukasSchmetz** [comment]
> @MWADCM @LukasSchmetz We need to change our KIT and migrate the API documentation to the API Hub (For all Released KIT Versions)

@ClosedSourcerer Thanks for highlighting. Should we link that to our KIT Maintenance Feature for R25.03?

**Comment by stephanbcbauer** [comment]
This feature is still planned, but directly after 25.03 because we need a time without contributions to the website. We will work on this after the KITs for 25.03 are merged and finalized.

**Comment by stephanbcbauer** [comment]
Meeting with @jSchuetz88 , @ther3sa 

**Preperation and planning**

1. All KITS 25.03 needs to be merged
2. TAG/Release erstellen for 25.03 -> as backub
3. api-hub needs to be adapted, [PR](https://github.com/eclipse-tractusx/api-hub/pull/29) -> in this case older versions are not deleted and are still available ... is needed for older KIT versions
4. KITs needs to be adapted (use of [api-hub](https://github.com/jSchuetz88/eclipse-tractusx.github.io/blob/move-open-api-yaml-files/.tractusx)) deletion of open API generated MDX files

**after this we are ready to work**

1. tractus-x website -> read only -> @stephanbcbauer otterdog
2. delete not needed plugins -> (open api and remote) -> @stephanbcbauer 
3. Communivation about read only via mailing list -> @stephanbcbauer 
4. update already existing [fork](https://github.com/tractus-x-community-days/eclipse-tractusx.github.io) -> @stephanbcbauer 
5. for each KIT seperate branch (solve mdx checker issues) -> branch is merged to main on fork -> @ther3sa , @jSchuetz88 , @stephanbcbauer 
6. IP issues is needed because of the huge amount of changes -> @stephanbcbauer 
7. merge fork main -> origin main -> @stephanbcbauer 

**optional**

1. Folderstructure renaming kebab-case
2. SVG -> draw.io renaming?
3. restructuring config files -> @jSchuetz88

**Comment by stephanbcbauer** [comment]
## Issue Template for KIT issues 

```Markdown

# <KIT Name> upgrade preperation 

Within this issues all the needed changes for "upgrading" the KIT to fit the requirements with docusaurus 3.X are tracked. The work is down on a seperate branch for each KIT on a specific fork.

To keep the changes small we are working KIT by KIT. For each PR on the fork from branch to main, we will do a official committer review, done by:
- @stephanbcbauer or
- @ClosedSourcerer or 
- @matbmoser 

For each PR an IP issue should be created. Assumption would be, that we dont need an ip issue for the big bang (merging everything to origin)

## Tasks

- [ ] Migrate KIT (links, sntax) to fit MDX Checker
- [ ] API Hub is linked, if needed
- [ ] KIT is running (local website build is succesfull)
- [ ] All versions of KIT are adapted
- [ ] Links/references are resolved 
- [ ] Review done by a committer
- [ ] IP issue created and approved

## Tasks (optional)

- [ ] folder and filenames -> kebap-case
- [ ] draw.io renaming
```

**Comment by stephanbcbauer** [comment]
Since we need a lot of audits and alignment, i also created an [Issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/20277) to collect the different ip issues

**Comment by stephanbcbauer** [comment]
@stephanbcbauer provided documentation "How to activate a KIT"

**Comment by ClosedSourcerer** [comment]
> - [ ] create branch on [fork](https://github.com/docusaurus-upgrade/eclipse-tractusx.github.io)


Fixed the fork link for you.
