### ISSUE TITLE
[Industry Core KIT] Release Checks

### ISSUE THREAD

**Issue by markuskeidl** [eclipse-tractusx/sig-release#986]
This issue tracks all relevant release checks for your KIT.

## Release Info

- Message-based exchange via EDC with notifcations: The goal is to standardized notifications regarding structure (standardized header with flexible content) and how their API is mapped to EDC (e.g., assets, properties). 
  - https://github.com/catenax-eV/sig-roadmap/issues/31 
- Add guidelines on when to use digital twins in a use case and when not to use
  - https://github.com/catenax-eV/sig-roadmap/issues/76
  - https://github.com/catenax-eV/sig-roadmap/issues/123 (related to issue above)
- Bugfixing, e.g.,
  - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/998 
    - not correctly merged into 24.08 with https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/980
    - Duplicate: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1068

**Version to be included in Eclipse Tractus-X release:** 1.2.0
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs witch included the changes for this version if possible.

- [PR number](pr-url)

# General

- [ ] **CHANGELOG** available and maintained
- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [x] **Vision and Mission** statement present
- [x] **Business Value** statement present
- [x] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [x] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] ~**Protocols** available (e.g., dataspace protocol)~
- [ ] ~**Sample Data** available~
- [x] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] ~**Reference Implementation** available~

# Operation View

- [ ] ~**Setup Guide** available (e.g., installation guides)~
- [ ] ~**Deployment Script** available (e.g., helm charts)~

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

# Todos

- [ ] Review by peer group (members of committees and expert groups of impacted use cases)
- [ ] Please link the open or merged PR that includes the changes.

**Comment by markuskeidl** [comment]
Pull request for notifications and digital twin guidelines: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1158

**Comment by ther3sa** [comment]
Hi @markuskeidl, 
could you provide an update on the current status? Is the release check issue ready, or should it be assigned to  25.06 due to remaining open issues?"

**Comment by ther3sa** [comment]
Since a few issues referenced here are still open, I am setting the milestone to 25.06

**Comment by ther3sa** [comment]
@markuskeidl @jSchuetz88 
Could you please give me an update on this issue to ensure transparency. 
Please check off any topics that have already been worked on or completed?

**Comment by ther3sa** [comment]
@markuskeidl @matbmoser @jSchuetz88 

Important!!
----------


If no update is provided here, this issue will be moved to the next release. I kindly ask for a status update to ensure transparency and to avoid blocking the process.

**Comment by jSchuetz88** [comment]
@ther3sa I fixed the last open issue (https://github.com/eclipse-tractusx/sldt-semantic-models/issues/723). I think this can be closed now.
