### ISSUE TITLE
Enhance and upgrade Umbrella Helm Chart (R24.08, R24.12)

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-release#994]
# Overview

## Explain the topic in 2 sentences

Continue the integration works to enable a sandbox environment - [umbrella helm chart](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-2.0.4/charts/umbrella/README.md).

## What's the benefit?

So that it is possible to have an easy entrance point for developers and adopters to experience our developments hands on but also to enable e2e testing.

## What are the Risks/Dependencies ?

All products, Eclipse Tractus-X overarching and continuous endeavour.

### Current implementation

see https://github.com/eclipse-tractusx/sig-release/issues/710

### Proposed improvements

- [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/128
- [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/133
- [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/150
- [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/95
- [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/158
- [x] https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/165

For a more detailed overview, please see the [Board](https://github.com/orgs/eclipse-tractusx/projects/80).

### Committer & Contributor

There are already Committers and Contributors involved in Eclipse Tractus-X overarching and continuous endeavour but we need to become more and especially all Committers should be involved.

## Additional Information

Join the [Umbrella Matrix Chat](https://chat.eclipse.org/#/room/#tractusx-umbrella-chart:matrix.eclipse.org) and our [weekly sync](https://eclipse-tractusx.github.io/community/open-meetings#Umbrella%20Helm%20Chart%20Sync).

**Comment by matbmoser** [comment]
I am willing to contribute

**Comment by evegufy** [comment]
all done except https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/162, which was remove from scope --> close
